### ISSUE TITLE
🐛 BUG: Partial<> isn't respected for the interface of props of a component

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#105]
### Describe the Bug

`Partial<>` isn't being respected for the interface of props of a component. The VSCode extension is marking all the properties as required.

### Steps to Reproduce

The VSCode extension should check if the interface used for components is wrapped with `Partail<>`

**Comment by Princesseuh** [comment]
Hello!

Is this still relevant? I can't seem to be able to reproduce. Using the following component

```astro
---
  interface Hello {
    hello: string,
    name: number
  }

  export type Props = Partial<Hello>
---
```
And the following code: 

![image](https://user-images.githubusercontent.com/3019731/166392235-6df77cd9-23ce-49d5-835a-68ac2a8da9ec.png)

I get no errors for missing props, as expected

**Comment by RafidMuhymin** [comment]
I am confirming that this issue is no longer relevant. Thank you for your contribution @Princesseuh!
