### ISSUE TITLE
VSCode: Hover hint isn't working for Javascript inside script tags

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#11]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Hover hint isn't working for Javascript inside script tags.

### Steps to Reproduce

The VSCode extension should enable hover hints for Javascript inside script tags.

**Comment by Princesseuh** [comment]
I can't pinpoint the commit because it was fixed before this repo even existed but the changelog says this feature was added in the 0.6.0 version (so about 6-7 months ago)

Please create another issue if this feature isn't working for you
