### ISSUE TITLE
VSCode: Autocomplete for JS, CSS/SCSS inside Astro components

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#12]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Currently, autocomplete doesn't work for JavaScript inside the script tags, CSS, and SCSS inside Astro components.,

### Steps to Reproduce

JavaScript Intellisense now works inside the frontmatter but not inside the script tags. It should work in both of the places. And CSS and SCSS IntelliSense should work inside the style tags.

**Comment by Princesseuh** [comment]
SASS unfortunately cannot be supported at this time because the VSCode's CSS language service only support CSS, LESS & SCSS

Just to update a bit the issue, CSS/SCSS completions should already be working in style tags. The only thing missing there is Emmet

**Comment by Princesseuh** [comment]
https://github.com/withastro/language-tools/pull/258 adds support for Emmet completions inside CSS

As such, the only remaining thing in this issue is completions inside of script tags. That is currently blocked by https://github.com/withastro/language-tools/issues/230
