### ISSUE TITLE
💡 RFC: Publish the VS code extension to Open VSX registry so it can be used in Gitpod.

### ISSUE THREAD

**Issue by sarah11918** [withastro/language-tools#121]
### Background & Motivation

I want to be able to use the Astro VS code Extension in Gitpod, but from their documentation... ([https://www.gitpod.io/docs/vscode-extensions#where-do-i-find-extensions](https://www.gitpod.io/docs/vscode-extensions#where-do-i-find-extensions))

> If you cannot find an extension by searching in Gitpod, it probably means that the extension hasn’t been added to the Open VSX registry yet. (https://open-vsx.org/)
> 
> In that case, please reach out to the extension author and politely ask them to publish their extension to the vendor-neutral, open source Open VSX registry. The ”How to Publish an Extension” docs provide step-by-step instructions.
> 
> Please note that .vsix files downloaded from the Visual Studio Marketplace should not be installed in Gitpod, because Microsoft prohibits the direct use of their marketplace by any non-Microsoft software, even though most extensions are actually open source and not developed or maintained by Microsoft.

### Possible solutions

Follow the steps at [https://github.com/eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (listed below) to publish the Astro VS code extension to the Open VPX registry. 

### Alternatives considered
There seem to be no other alternatives if we want Gitpod users to be able to use the VS code extension.
### Risks, downsides, and/or tradeoffs
???
### Open Questions
Is there any downside to doing this?

### Detailed Design

Detailled instructions are published at [https://github.com/eclipse/openvsx/wiki/Publishing-Extensions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions), but the steps are:

How to Publish an Extension
1. Create an Eclipse account
2. Log in and sign the Publisher Agreement
3. Create an access token
4. Create the namespace
5. Package and upload

GitHub Action
You can find a GitHub action that allows publishing to Open VSX at HaaLeo/publish-vscode-extension.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by RafidMuhymin** [comment]
@sarah11918 It's already being discussed at #16

**Comment by sarah11918** [comment]
Closing, since it's at [#16](https://github.com/withastro/language-tools/issues/16)
