### ISSUE TITLE
🐛 BUG: Type errors aren't shown for imported interfaces and types

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#126]
### Describe the Bug

The VSCode extension doesn't display type errors for imported interfaces and types.
![Peek 2021-12-03 23-24](https://user-images.githubusercontent.com/63650415/144651211-59fe832a-ed99-4600-bee1-8a51ca36a4fe.gif)

### Steps to Reproduce

The VSCode extension should display type errors for imported interfaces and types.

**Comment by Princesseuh** [comment]
This is a TypeScript issue, TypeScript expects you to not put any file extension (or .js) when importing TS files

Nonetheless, since Astro recommend (or at least used to) to put the file extension, we should make sure that it works even when you put the extension, good catch

**Comment by Princesseuh** [comment]
Now that the extension recommend TypeScript compatible imports, this shouldn't be a problem anymore. Closing
