### ISSUE TITLE
🐛 BUG: NIT: Rename project from `astro-language-tools` to `language-tools`

### ISSUE THREAD

**Issue by jonathantneal** [withastro/language-tools#136]
### Describe the Bug

With the change from `snowpack` to `withastro`, the `astro-compiler` project was renamed `compiler`, so this project should be named `language-tools`.

### Steps to Reproduce

1. Visit the `withastro` community.
2. Consider the importance of names. "_What’s in a name? That which we call a rose by any other name would smell as sweet._" — Romeo and Juliet (Act 2, Scene2)
3. Consider the impact Shakespeare has had on society.
4. Consider whether we crave consistency for objective or subjective reasons.
5. Error! You’re thinking too much! Just rename it or don’t.

**Comment by aFuzzyBear** [comment]
"Without that title, doff thy name, and for that name which is no part of thee," ....😂
