### ISSUE TITLE
🐛 BUG: `client:` attributes not being parsed correctly

### ISSUE THREAD

**Issue by ProspectPyxis** [withastro/language-tools#141]
### Describe the Bug

At least with the `framework-solid` template, the Astro extension seems to not parse `client` attributes in imported components correctly, giving an incorrect error. Everything works fine otherwise.

### Steps to Reproduce

1. `pnpm create astro` using template `framework-solid` (npm or yarn likely does the same thing, but I haven't tested this)
2. Open the resulting project in vscode, with only the Astro plugin enabled
3. Open the `index.astro` file
4. The line `<Counter client:visible>` throws an error:
  ```
  Type '{ "client:visible": true; }' is not assignable to type '{ children: any; }'.
    Property 'client:visible' does not exist on type '{ children: any; }'.js(2322)
  ```

**Comment by ProspectPyxis** [comment]
Update: this issue seems to only happen with `.jsx` files. After simply renaminng `Counter.jsx` to `Counter.tsx` with no other changes to the file and changing the `import Counter` statement appropriately, the issue disappears. Thankfully, I'm planning to code in typescript, so this issue won't affect me in this case, but I'll leave this open for investigation in case other people runs into the same issue and wishes to use javascript.

**Comment by Simperfy** [comment]
I'm experiencing the same issue as well.

**Comment by snelgrove** [comment]
I'm using Typescript (and Svelte, if that's relevant) and I get a very similar message :
```ts
Type '{ "client:load": true; list: any; }' is not assignable to type 'IComponentOptions<Record<string, any>>'.
  Property 'client:load' does not exist on type 'IComponentOptions<Record<string, any>>'.
```
No idea why, but the error seems to disappear if I delete `tsconfig.json`.

**Comment by PoQuatre** [comment]
This issue is happening to me for `.tsx` files while strict mode is enabled in `tsconfig.json`.
PS: I'm using Preact (with Typescript)
