### ISSUE TITLE
🐛 BUG: Import svelte or vue files

### ISSUE THREAD

**Issue by vhladko** [withastro/language-tools#142]
### Describe the Bug

If you are using latest templates and in your tsconfig file has:
```
compilerOptions: {
  moduleResolution: "node",
}
```
And try to import `svelte` or `vue` components to your astro component, you will get and error from extension.

### Steps to Reproduce

1. `npm init astro` using template vue/svelte
2. import svelte or vue component into your astro component
3. Error! Astro extension will show you an error 
![Screenshot 2021-12-30 at 10 11 14](https://user-images.githubusercontent.com/56257437/147733439-15960b78-6dc7-46bd-ad07-ca1c77559acb.png)

**Comment by dslatkin** [comment]
Also had the same issue! The `.tsconfig` mentioned here that comes with the default Svelte template seemed to be causing it, removing the file (presumably meaning I'm going with just JS for now) seems to fix the issue. Thanks to Erika and Muhymin in the Discord for the help!

**Comment by jonathantneal** [comment]
This is as far as I got:
- Svelte files in the frontmatter of an Astro file are not being run thru the checks, like `isVirtualSvelteFilePath`. Maybe that’s how it’s supposed to work.
- I was able to narrow down that the checks might be happening in this file  (`packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts`) maybe in `getDiagnostics`.
