### ISSUE TITLE
🐛 BUG: Property 'env' does not exist on type 'ImportMeta'

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#147]
### Describe the Bug

The VSCode extension is displaying `Property 'env' does not exist on type 'ImportMeta"` when trying to access `import.meta.env` in `.astro` files. I didn't experience this issue with the previous releases of the extension. So, I think the issue has been introduced in `v0.8.6`.

### Steps to Reproduce

The VSCode shouldn't display any error when trying to access `import.meta.env`

**Comment by RafidMuhymin** [comment]
Though adding `"types": ["vite/client"]` to the `tsconfig.json` file removes the error in `.jsx/.tsx` files but not in `.astro` files. So, it must be a problem related to the extension.

**Comment by jonathantneal** [comment]
Fixed in https://github.com/withastro/language-tools/pull/151 🎉
