### ISSUE TITLE
🐛 BUG: Error when destructuring children parameter of (P)react components

### ISSUE THREAD

**Issue by cpetrov** [withastro/language-tools#152]
### Describe the Bug

When destructuring `children` from the parameters of a (P)react component, e.g.:

```jsx
import { h } from 'preact';
import Styles from './styles.module.scss';

function Button({ children }) { // <<<
  return <span className={Styles.button}>{children}</span>;
}

export default Button;
```

... following error will be shown at the place of usage, even when the component has JSX children:

```jsx
<Button>View All</Button>
// Property 'children' is missing in type '{}' but required in type '{ children: any; }'.
```

Not destructuring the parameters instead works around the error:

```jsx
...
function Button(params) {
  return <span className={Styles.button}>{params.children}</span>;
}
...
```

### Steps to Reproduce

Tested with `create-astro@0.7.0` and VSCode Astro extension v0.8.6.

1. `npm init astro` using template Portfolio
2. Open `src/pages/index.astro` and navigate to [L218: `<Button>View All</Button>`](https://github.com/withastro/astro/blob/create-astro%400.7.0/examples/portfolio/src/pages/index.astro#L218). An error will be shown in VSCode.

**Comment by Princesseuh** [comment]
Closed by https://github.com/withastro/language-tools/pull/216
