### ISSUE TITLE
🐛 BUG: If a variable starts with source and is compared with <, an error is shown

### ISSUE THREAD

**Issue by GrafZ3pp3lin** [withastro/language-tools#155]
### Describe the Bug

This error occurs in vscode with the Astro extension.

If a variable in the frontmatter script starts with source and is compared with the smaller symbol (<) and later at some point a larger symbol (>) comes, an error is displayed in vscode.

![image](https://user-images.githubusercontent.com/40472792/149999646-b0edbeb9-ada4-4699-8079-c2412fef4a8b.png)
![image](https://user-images.githubusercontent.com/40472792/150000750-43b05123-9ab8-4dfb-9441-5eb0d5ced7f3.png)

### Steps to Reproduce

1. `npm init astro -- --template minimal`
2. start a variable with source in the frontmatter script
3. Compare the variable with <
4. Use somewhere in the Frontmatter script the > symbol
5. Error!

**Comment by Princesseuh** [comment]
This is caused by [this line](https://github.com/withastro/language-tools/blob/2910b038e1408940c6ecc8b9217d9d5684598ef2/packages/language-server/src/plugins/typescript/astro2tsx.ts#L50) as it fails with any of the cases in it (`hr`, `meta` etc)

Will see what I can do, thanks for the report!
