### ISSUE TITLE
🐛 BUG: Invalid Regex

### ISSUE THREAD

**Issue by JuanM04** [withastro/language-tools#165]
### Describe the Bug

When I was trying to add the new grammar definitions to GitHub linguist, it threw these errors:

```
2 errors found in new grammar 'repository `vendor/grammars/astro` (from https://github.com/withastro/language-tools.git)':
- Invalid regex in grammar: `text.html.astro` (in `packages/vscode/syntaxes/astro.tmLanguage.json`) contains a malformed regex (regex "`(?<=<(?i:script)[^>]*>)(?!\G)`": lookbehind assertion is not fixed length (at offset 22))
- Invalid regex in grammar: `text.html.astro` (in `packages/vscode/syntaxes/astro.tmLanguage.json`) contains a malformed regex (regex "`(?<=<(?i:style)[^>]*>)(?!\G)`": lookbehind assertion is not fixed length (at offset 21))
```

### Steps to Reproduce

1. Setup github/linguist
2. Run `script/add-grammar --replace astro https://github.com/withastro/language-tools`

**Comment by FredKSchott** [comment]
Ah nice! cc @jonathantneal can you prioritize? I would be that this is breaking some consumers who have already been updated.

**Comment by FredKSchott** [comment]
Ah nice find! @JuanM04 do you know enough to fix in the `astro.tmLanguage.json`file? Otherwise @jonathantneal can help work with you on a fix. I would bet that this is already breaking some consumers who have already been updated to the new URL.

**Comment by JuanM04** [comment]
@FredKSchott I can give it a try, although I don't know a lot about grammars

**Comment by jonathantneal** [comment]
Hi @JuanM04, @FredKSchott, I’m looking into this:

> lookbehind assertion is not fixed length

I’ll see how I can change this. Is this an additional restriction we need to look out for? Is there a list somewhere?

**Comment by JuanM04** [comment]
@jonathantneal maybe this [file of errors](https://github.com/github/linguist/blob/master/tools/grammars/compiler/errors.go) help, but if you wanna be sure, you can go through their "Updating a language url" guide

**Comment by jonathantneal** [comment]
I’m trying to split the language definitions out into two paths, one for `script` and one for `style` so that the lookbehind can be avoided. Our syntax narrows the range to within one of those before the lookbehind, which is why it works for our users. However, working on GitHub is pretty critical, so hopefully this split will let everybody win.

**Comment by jonathantneal** [comment]
@JuanM04, would you know if `script/add-grammar --replace astro https://github.com/withastro/language-tools` finds all errors, or stops early?

I ask because I see we 10 look-behinds (groups beginning with `?<=`) with zero or more occurrence matches within them.

**Comment by FredKSchott** [comment]
it sounds like the fixed-length is the issue? From the error message: `lookbehind assertion is not fixed length`

**Comment by jonathantneal** [comment]
That’s the same assumption that I’m working off. However, while trying to remove those 2 look-behinds, I saw that we had 8 more, some of which I had just duplicated to fix this one. I didn’t want to play wack-a-mole with GitHub.

**Comment by JuanM04** [comment]
@jonathantneal No idea. I'm looking for a way to test the grammar without doing all the cloning

**Comment by jonathantneal** [comment]
Thanks, @JuanM04. I’ll try to take it from here. I’m learning how to get `gem` going. P.S. Appreciate the [docs](https://github.com/github/linguist) 🙏!

**Comment by JuanM04** [comment]
@jonathantneal I've opened a PR that should fix this.

Btw, I've found a way to test with linguist faster:

1. clone the linguist repo
2. Run `script/bootstrap`
3. Copy the `language-tools` repo into `linguist/astro`
4. Run `script/grammar-compiler add astro`
