### ISSUE TITLE
🐛 BUG: Starting with 0.9.1 the linter doesn't find name "Astro" or property "env" (with Astro version 0.23.7) 

### ISSUE THREAD

**Issue by moritzlaube** [withastro/language-tools#185]
### Describe the Bug

As described in the Troubleshoot section, the language tool isn't recognizing Astro and property env anymore as soon as I upgraded to version 0.9.1. I do have Astro version 0.23.7. 

Downgrading to the last version 0.8.10 solves that issue. Does anyone else experience this issue?

### Steps to Reproduce

1. installing v 0.9.1
2. upgrading to Astro 0.23.7

**Comment by donovanchilders** [comment]
Yes, I can confirm this started in the last day or two for me.

**Comment by Princesseuh** [comment]
Hmm, that's weird. Just tested on a new project using 0.23.7 and the latest version of the extension and everything works as intended

What OS are you on and what package manager are you using?

**Comment by matthewp** [comment]
@Princesseuh I think it happens if you have no tsconfig.

**Comment by RafidMuhymin** [comment]
@matthewp and @Princesseuh I don't use any tsconfig files and I am not getting this error. So, I don't think this is related to the issue.

**Comment by godefroi** [comment]
I have a tsconfig.json file and I'm seeing the error.

**Comment by Princesseuh** [comment]
Thank you for sharing your `tsconfig.json`, is this using the latest version of the extension? (0.12.0 at the time of writing)

**Comment by godefroi** [comment]
Yes, as of last night it was 0.12.0. Now it's 0.12.1 and it's still happening.

**Comment by Princesseuh** [comment]
Hmm, interesting. I'm terribly sorry about this 😓 I still haven't been able to reproduce it unfortunately, an user even sent me their project where it was happening for them and there was no error when the same project was on my computer, tricky

Here's a solution that could potentially work in the meantime, add the following in your `tsconfig.json`: `types: ['astro/env']`

If it doesn't work, you might have to revert to 0.8.10 unfortunately until we can find a fix 😓

**Comment by godefroi** [comment]
Adding that to the tsconfig fixes the issue; TS now recognizes `Astro` as `Readonly<AstroGlobal>`.

**Comment by moritzlaube** [comment]
I still have that issue with `import.meta.env`. It says `Property env does not exist on tyoe ImportMeta`.

**Comment by Princesseuh** [comment]
> I still have that issue with `import.meta.env`. It says `Property env does not exist on tyoe ImportMeta`. 

Just to be sure, are you in an Astro file?

**Comment by moritzlaube** [comment]
Yes I am. My tsconfig looks like this. Am I doing something wrong? Thanks!

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "component:*": ["src/components/*"],
      "layout:*": ["src/layouts/*"]
    },
    "types": ["astro/env"]
  },
}
```

**Comment by Princesseuh** [comment]
Just updating a bit here, I still have no idea what causes this, unfortunately 😓I hear about this issue very very rarely, in the past month or so I have only heard about it once or twice from other users, but it's still seem to exist

@donovanchilders told me today that the issue magically fixed itself on their end even though there's been no code changes that could fix this since the introduction of the bug, which does adds to my confusion, but at least reassure me that the issue might be fixed for some users

If you still encounter this issue using the latest version of Astro itself and the latest version of the extension, please share any info you might have as you might be the key to finally crack this issue open!

**Comment by moritzlaube** [comment]
I just migrated to v1 beta and also update the language tool to 0.16.1.. For me, the issue seems to be gone. Thanks so much Erica (I hope it was Erica, if I'm not mistaken.) :)

**Comment by colinthedev** [comment]
Changing settings in my tsconfig file DID solve this problem across two different projects. This is the standard tsconfig.json that i use in both projects.


```
{
	"compilerOptions": {
		// Enable top-level await, and other modern ESM features.
		"target": "ESNext",
		"module": "ESNext",
		// Enable node-style module resolution, for things like npm package imports.
		"moduleResolution": "node",
		// Enable JSON imports.
		"resolveJsonModule": true,
		// Enable stricter transpilation for better output.
		"isolatedModules": true,
		// Add type definitions for our Vite runtime.
		"types": [
			"vite/client"
		],
		"typeRoots": [
			"./node_modules/@types",
			"./src/types"
		]
	},
	"compileOnSave": false,
	"exclude": [
		"src",
		"wwwroot"
	],
	"include": [
                 // An empty object lives in this file for the compiler
		"required.ts"
	]
}
```
