### ISSUE TITLE
🐛 BUG: CSS completions only work in the first style tag in a document

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#202]
### Describe the Bug

This is caused by a Svelte-ism in the way we recuperate the content of style tags. Since in Svelte you can only have one style tag per component, this is not an issue but in Astro files, you can realistically have multiple style tags 

The [offending code is (partly) here](https://github.com/withastro/language-tools/blob/fd92a856293febb71079a2163842ca7f7d462f0d/packages/language-server/src/core/documents/utils.ts#L255-L263). 

Probably what should happen is that our document should contain a list of style tags (array of TagInformation) and whenever we do operation in our CSSPlugin, we first check in which style tag we are and then give appropriate responses (we can have multiple style tags with different langs in a single page and thus needing different completions depending on that for instance)

### Steps to Reproduce

1. Create an Astro file with multiple style tag
2. Get completions in the first one
3. But not in the second one (or any after)!

**Comment by matthewp** [comment]
Oh good catch!
