### ISSUE TITLE
🐛 BUG: Shorthand syntax for props is not supported

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#225]
### Describe the Bug

Trying to use the shorthand syntax for props currently lead to an error, ex:

```astro
<Component {myProp}/>
```

We should support this, especially since it's a possible formatting result from the Prettier plugin

### Steps to Reproduce

1. Create an Astro project
2. Create a component with a prop
3. Try to pass a prop using shorthand syntax
4. Error!

**Comment by jonathantneal** [comment]
Here is a reproduction of the issue. It should automatically run `astro check` to see the issue. 

https://stackblitz.com/edit/github-jcxxvc?file=src%2Fpages%2Findex.astro&on=stackblitz

It seems like the language tools extension is interpreting the values as the props themselves.
