### ISSUE TITLE
🐛 BUG: at (@) attributes are not properly supported

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#247]
### Describe the Bug

The way the Astro Language Server does TypeScript support [is by first converting](https://github.com/withastro/language-tools/blob/main/docs/internal/language-server/plugins/typescript.md#tsx-generation) `.astro` files to TSX. This works nicely, however JSX has a few limitations that Astro does not have, namely, JSX does not support attributes starting with `@` so what we do is instead replace those `@` with `_`, which has worked without issues for months now

However, we're now much stricter regarding type checking, providing type checking for props in components, attributes on HTML elements etc which mean that.. TypeScript is complaining that `_thing` doesn't exist because it's actually `@thing` :sweat:

This is not an issue that affects only us either, for instance, Alpine.js users who like to use it with JSX have to put their templates in strings to render them to avoid issues

## Possible solutions

**For HTML attributes:**
We could add a setting to allow unknown attributes on HTML elements. We can't make this the default otherwise we'd lose that nice thing where you get an error when using unknown attributes

**For components**
When converting a component to TSX (that goes for Astro, Svelte and in the future Vue, components), we could also convert the props definition to use `_` instead of `@`

In both cases, we'd need to postprocess hover info, diagnostics etc etc to use `@` instead of `_` to avoid user confusion

### Steps to Reproduce

1. Create an Astro project
2. Try to use `@` attributes on anything (html elements, components etc)
3. Get a bunch of errors

**Comment by jonathantneal** [comment]
If the attribute/prop transform included a sourcemap, would you know if the language tools could factor that in?

If that is possible, or if we don’t know if its _impossible_, then I would be happy to take a look, maybe using a tool like [`magic-string`](https://www.npmjs.com/package/magic-string) to make the conversion in the source only, and avoid reaching into the connected files.

Thoughts?
