### ISSUE TITLE
🐛 BUG: `---` in JS comment breaks frontmatter

### ISSUE THREAD

**Issue by mattrossman** [withastro/language-tools#248]
### Describe the Bug

Including `---` in JS comments within component frontmatter causes syntax errors in the rest of the file.

This is probably not a very common occurence, but it's off-putting for beginners since it appears in the "hello world" example from the manual installation documentation.

### Steps to Reproduce

I'm following the Astro manual installation guide. I copied and pasted the basic `index.astro` file from here: https://docs.astro.build/en/install/manual/#3-create-your-first-page

```astro
---
// Welcome to Astro! Everything between these "---" code fences
// is your "component front matter". It never runs in the browser.
console.log('This runs in your terminal, not the browser!');
---
<!-- Below is your "component template." It's just HTML, but with
     some magic sprinkled in to help you build great templates. -->
<html>
  <body>
    <h1>Hello, World!</h1>
  </body>
</html>
<style>
  h1 {
    color: orange;
  }
</style>
```

VSCode underlines everything after the fenced region in red, with the error:

```
The right-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.ts(2363)
```

If I remove the JS comment containing `---` then the errors go away.

**Comment by Princesseuh** [comment]
Ah yes, our detection of the frontmatter right now is very naive. I'm (unfortunately) not surprised, will see what I can do

Thank you for the report!

**Comment by Princesseuh** [comment]
Update on this, https://github.com/withastro/language-tools/pull/335 fixed the syntax errors, however there's still some weird behaviour notably around completions.

The cause is still the same, our parsing is naive and just look for `---` to determine the end of the frontmatter

**Comment by calebeby** [comment]
@Princesseuh would it be an improvement to just only scan for `---` to be at the beginning of lines? I think that would fix a lot of cases (not all) and would be straightforward to implement.

For example, it would fix parsing code like this:

```astro
---
console.log(/---/g);
---
```

But not like this:

```astro
---
/* this is a comment
---
*/
---
```

**Comment by Princesseuh** [comment]
The real, perfect solution would be to entirely remove the `parseAstro.ts` file completely, replacing it with a parse step from the Astro compiler instead, so we're sure it's 100% accurate (plus, the AST it provides would allow us to do some things we can't do right now)

But yeah, it would be an improvement to at least limit it to the beginning of the line
