### ISSUE TITLE
🐛 BUG: file imports with query params reports "cannot find module" error

### ISSUE THREAD

**Issue by dustinsgoodman** [withastro/language-tools#256]
### Describe the Bug

When using `vite-imagetools`, the tool recommends importing images using query strings to specify image dimensions, format, etc. to be pass into its image processor. Astro's language server cannot parse the path without the query string thus causing the issue. Screenshot example below:

![image](https://user-images.githubusercontent.com/1815379/164345156-22718bb9-854c-48a6-83bb-2a201f415a8a.png)

Astro version: 0.26.1
OS: OSX
Editor: VS Code

### Steps to Reproduce

1. `npm init astro` using template blog
2. Install `vite-imagetools`
3. Add to astro config using default settings:
  ```
    vite: {
      plugins: [imagetools()],
    },
```
5. Attempt to import an image using query strings
6. Get lint error that module cannot be found. Expect no error instead.

To save time, [here's a PR](https://github.com/dustinsgoodman/dustingoodman.dev/pull/68) in a repo you can clone. Look at `src/components/Header.astro` for the error.

https://github.com/dustinsgoodman/dustingoodman.dev/pull/68/files#r854671243

**Comment by Princesseuh** [comment]
I don't think this issue is on us unfortunately, 

Due to a limitation in TypeScript, image-tools does not support it. See the following issue https://github.com/JonasKruckenberg/imagetools/issues/70

**Comment by dustinsgoodman** [comment]
Totally fair and very reasonable response! Wasn't quite sure if it was you all or not but figured I could drop this in here just in case. That first link you shared has a promising looking solution. I'll give that shot and post back here but I'll close this as I can get behind it not being on you all. Thanks for your help!
