### ISSUE TITLE
🐛 BUG: SVG tag doesn't support `set:html`

### ISSUE THREAD

**Issue by davidwarrington** [withastro/language-tools#260]
### Describe the Bug

I'm not certain if this is the correct place for the issue, so if it belongs in another repo please point me there.

Adding `set:html` to an SVG tag results in the following error in VSCode

![image](https://user-images.githubusercontent.com/9138568/164978353-ad79a5ef-1880-4751-a12b-3d8d5c3b430a.png)

```
Property 'set:html' does not exist on type 'SVGProps<SVGSVGElement>'.
```

### Steps to Reproduce

1. `npm init astro` using any template
2. Create an empty `.astro` component file
3. Add `<svg set:html={''}></svg>`
4. Error! VSCode reports that this is an error however Astro can still render this properly.

**Comment by Princesseuh** [comment]
This is the right repo 😄Good catch, I did in fact forget to add it to SVG elements!

Thank you for creating an issue
