### ISSUE TITLE
🐛 BUG: solid's control flow elements can't infer children props

### ISSUE THREAD

**Issue by ProspectPyxis** [withastro/language-tools#276]
### Describe the Bug

Solid's control flow elements (`<Show>`, `<For>`, etc.) requires children elements to be passed. However, using the normal syntax with closing tags throws an error in the editor, requiring you to directly define the `children` prop manually. The component does compile when running `npm run dev`, so I can confirm it's just an editor issue.

### Steps to Reproduce

1. Start a new astro project with `npm create astro@latest`. Select the "Completely empty" template, and enable solidjs integration.
2. In `src`, create a new `.tsx` file and paste in the following:
```tsx
import { Component, For, Show } from 'solid-js'

const TestComponent: Component = () => {
  return (
    <div>
      <Show when={true} children='Hello world!' />
      <For each={[1, 2, 3]} children={(num) =>
        <p>{num}</p>
      } />
    </div>
  )
}

export default TestComponent
```
3. Neither components should throw an error.
4. Replace the div's contents with the following:
```tsx
      <Show when={true}>Hello world!</Show>
      <For each={[1, 2, 3]}>{(num) =>
        <p>{num}</p>
      }</For>
```
5. Both `<Show>` and `<For>` now throws an error:
![errorscreenshot](https://user-images.githubusercontent.com/25642180/167287691-286e5556-87a1-461c-b5ec-8ea99eff1f88.png)

**Comment by Princesseuh** [comment]
This extension does not operate inside `tsx` files, you probably have the wrong `tsconfig.json` settings for Solid

**Comment by ProspectPyxis** [comment]
Ah, oops. :sweat_smile:
Apologies for the user error, it only happened when I was using solid so I assumed, haha.
