### ISSUE TITLE
🐛 BUG: Astro syntax highlighting broken on comments inside of elements

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#278]
### What version of `astro` are you using?

1.0.0.beta-7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Zorin OS

### Describe the Bug

Shiki isn't highlighting comments inside JS objects written using the syntax `/* */` properly. This affects both the `<Code />` component and Astro code blocks inside markdown.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wnuztx

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by FredKSchott** [comment]
@Princesseuh I would expect this to work however, and right now it highlights incorrectly:

```astro
<Picture
  src="https://picsum.photos/200/300"
  alt="A random image"
  <!-- five breakpoints will be generated ranging from 200px to 1000px -->
  breakpoints={{ count: 5, minWidth: 200, maxWidth: 1600 }}
/>
```

**Comment by FredKSchott** [comment]
Just chatted with Nate and that's actually not valid HTML! You can't have an HTML comment mixed in with your attributes.

Nate said that JSX-style comments will still work though, if you need it.

```astro
<Picture
  src="https://picsum.photos/200/300"
  alt="A random image"
  {/* five breakpoints will be generated ranging from 200px to 1000px */}
  breakpoints={{ count: 5, minWidth: 200, maxWidth: 1600 }}
/>
```
