### ISSUE TITLE
🐛 BUG: Vue template doesn't work out of the box

### ISSUE THREAD

**Issue by TheDutchCoder** [withastro/language-tools#279]
### What version of `astro` are you using?

0.22.18

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

The Vue starter has all kinds of issues out of the box:
1. There's no Vue shim, so TS can't deal with Vue SFC files
2. The tsconfig is empty (except for moduleresolution), so TS won't pick up Vue files properly anyway
3. The Vue component throws error because of 1 and 2
4. The index.astro file contains a `<style global>` tag that throws a JS type error: `Type '{ global: true; }' is not assignable to type 'ElementAttrs<StyleHTMLAttributes>'.
  Property 'global' does not exist on type 'ElementAttrs<StyleHTMLAttributes>'.js(2322)`

I can't seem to fix 4 at all, so I don't know how to proceed, but these all seem like very important missing things?

Note: Stackblitz won't show you the errors, you can literally add anything to the astro template and it'll be fine with it (I've added a bogus and invalid meta element as an illustration), this needs to be tested locally in a real IDE like VSCode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-uhx2lz-uxjhxt?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by matthewp** [comment]
Transfered to language-tools since these all relate to TS issues in VSCode when using Vue. @Princesseuh has done recent work on this with React.

**Comment by Princesseuh** [comment]
I believe all the issues here have been fixed :smiley:

Some additional settings inside `tsconfig.json` or a `jsconfig.json` might be needed for ex: full Volar support depending on if you want to use TS or JS etc but there shouldn't be any errors at least!

Don't hesitate to open another issue if there's anything!

**Comment by CDHon** [comment]
> I believe all the issues here have been fixed 😃
> 
> Some additional settings inside `tsconfig.json` or a `jsconfig.json` might be needed for ex: full Volar support depending on if you want to use TS or JS etc but there shouldn't be any errors on our side at least!
> 
> Don't hesitate to open another issue if there's anything!

I download the Astro Framework Vue Example, but volar does not work
