### ISSUE TITLE
🐛 BUG: in neovim, repeatedly formatting .astro files adds the last line over and over

### ISSUE THREAD

**Issue by hayley** [withastro/language-tools#293]
### Describe the Bug

Unfortunately, I just started trying out this setup last night, so I'm not sure what all info I can include.

It seems that I made the switch coincidentally after formatting was added in #277 so I can't speak to what was happening prior to that commit.

And the formatting is repeatedly adding the last html tag to the document over and over (later edit: it's repeating the last line over and over regardless of content).

See the comparison here of a brand new setup of the `minimal` template versus after I've saved the file 10+ times with format-on-save enabled.

https://github.com/hayley/astro-formatting-bug/compare/69ea84c4da1410a9c07501e8c1c51c243f2d3879...cb3861b8b841e178f726519cdc182bcb236f1605

Example after formatting a few times:
```
<body>
  <h1>Astro</h1>
</body>

</html>

</html></html></html>
```

I'm using a fairly out of the box LunarVim setup (https://github.com/LunarVim/LunarVim).

notes:
* it doesn't seem to matter whether the language server is directly included in the project's package.json or just installed globally on the system
* it doesn't seem to matter what the last HTML tag is (e.g. I have an `.astro` file where it endlessly repeats `</article>` on save)
* happening on both LunarVim stable and rolling
* happening on every single `.astro` file I've tried
* happening on a mac and a Void Linux box

It's been ages since I've used (n)vim standalone for development, otherwise, I would've figured out how to test this in something that wasn't lunarvim. I'm assuming this issue isn't lunarvim directly, but I will update this issue if I do successfully get the LSP stuff working in a different (n)vim setup and notate if the same problem is/isn't happening.

Edit: also to clarify, I've tested formatting on save with expected results on `.svelte`, `.js`, and `.json` files so it seems that the formatting on save is working as expected in general.

### Steps to Reproduce

1. `npm init astro` using template minimal
2. use LunarVim to edit an astro file
3. install the astro LSP if it isn't already - the following will bring up the LSP installer window: `space l I` (if the font here is hard to read, it's space, lowercase l as in lima, uppercase I as in India)
4. `:set filetype=astro` since lunar doesn't seem to auto-detect `.astro` files 
5. save the file and watch how it will endlessly append the last HTML tag to the end of the file on each save

**Comment by Princesseuh** [comment]
Ah yes I have seen that issue happens during development, I thought I had fixed it :thinking: That one should be simpler fix. On VS Code at least, if you format again it'll put it back to the beginning of the line

The issue linked is about another problem, it was posted before formatting was added
