### ISSUE TITLE
🐛 BUG: In non-Astro workspaces, the extension warn about not being able to find Astro abusively 

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#296]
### Describe the Bug

Currently, when opening Astro files outside of an Astro workspace, the extension will complain about not being able to find Astro. This is valid, however it's very annoying for users. It'd be great if the following happened:

- If an Astro file is opened inside a non-Astro workspace, we should warn once, and only once about not being able to find Astro and that the experience might be degraded
- When multiple workspaces (folders) are opened, we should check if the folder is an Astro project before warning. Otherwise, users see the warning for every single folder, which is very annoying, especially considering those folders are not even Astro related

Those two behavior are pretty undesirable, we should make sure the extension is helpful in cases where it matters and otherwise be as invisible as possible 

### Steps to Reproduce

1. Open an Astro file in an untitled workspace
2. Extension warn multiple times about not being able to find Astro

1. Open multiple folders, with one of them being an Astro project
2. Extension warn that Astro couldn't be found in every opened folder

**Comment by Izzur** [comment]
Alternatively it would be helpful to add extension setting to disable Astro extension warning altogether
