### ISSUE TITLE
💡 RFC: Add support for selection ranges

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#309]
### Background & Motivation

Selection ranges are used for commands / shortcuts like `Expand / shrink selection`. The commands work without them but they're not as smart, instead using a simple word-based algorithm instead of actually understanding the language being selected

We should support them, as they're pretty handy for navigating code through shortcuts, especially for advanced users used to them in JavaScript

### Possible solutions

This should be able to be easily provided by our usual language service (vscode-html-languageservice, vscode-css-languageservice and TypeScript). A selection range could be added for the frontmatter, not sure if it's necessary though

### Alternatives considered

N/A

### Risks, downsides, and/or tradeoffs

N/A

### Open Questions

N/A

### Help make it happen!

- [x] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by agos** [comment]
I tried this today inside VS Code without success - is some other piece needed to have it work?
