### ISSUE TITLE
🐛 BUG: all open tabs + editors are closed when opening a workspace with an outdated version of Astro

### ISSUE THREAD

**Issue by Enteleform** [withastro/language-tools#315]
### Describe the Bug

# Expected

✔️ error message is displayed, prompting user to upgrade Astro  
✔️ tabs & editors remain intact  

# Actual

✔️ error message is displayed, prompting user to upgrade Astro  
❌ tabs & editors remain intact  

https://user-images.githubusercontent.com/10906415/172441755-d176d741-6a0b-42e0-a3ae-159daceb5a51.mp4

![ScreenToGif_2022-06-07_13-06-36](https://user-images.githubusercontent.com/10906415/172442154-2718700b-f766-412f-bc88-21a8d15f143f.png)

### Steps to Reproduce

1. close a VSCode workspace, leaving it with some arbitrary tab/editor layout
2. reopen the workspace
3. after a few seconds, an error is displayed and all tabs & editors are closed

**Comment by Princesseuh** [comment]
Hmm, that's weird. We don't touch tabs and editors at all, might be a side effect of something else..

I'll check

**Comment by Enteleform** [comment]
@Princesseuh just ran into this issue in a non-Astro project, seems like the error message timing & Astro project context was just coincidental. I'll close the issue for now and reopen if anything changes, I think it's probably related to some other plugin though.
