### ISSUE TITLE
🐛 BUG: Alpine Example's x-data can't work with vscode extension,  give a  '{' expected  error.

### ISSUE THREAD

**Issue by CDHon** [withastro/language-tools#319]
### Describe the Bug

![image](https://user-images.githubusercontent.com/79888915/173262937-0875374d-447d-4d66-9fca-de17200768cc.png)

### Steps to Reproduce

1. Download  https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-alpine?file=src/components/Counter.astro or my fork: https://stackblitz.com/edit/github-b1i4fe?file=src/components/Counter.astro
2. run pnpm i
3. open .\src\components\Counter.astro
4. add or change the property ( const { /* anything in here */} = Astro.props)
5. x-data can't work, give a '{' expected error.

**Comment by CDHon** [comment]
I disable the extension and open it again, then the error was gone

**Comment by CDHon** [comment]
I have to set "astro.typescript.diagnostics.enabled" as false

**Comment by Princesseuh** [comment]
The issue here is that we don't support template literals as attributes values directly at the moment. 

Wrapping it in a JSX expression should work. Ex: `x-data={`content`}`
