### ISSUE TITLE
🐛 BUG: Formatter adds empty new lines when using < operator

### ISSUE THREAD

**Issue by makifoxgirl** [withastro/language-tools#324]
### Describe the Bug

When I use operator < or <=, the formatter freaks out and starts adding new lines in html. It might think the operator is the start of a new html tag or something but it's clearly in the javascript section, even when it's commented it still happens. Take a look at this video to get a better idea:

https://user-images.githubusercontent.com/8362329/175117921-e29e1bc1-f22c-49f0-9f10-2772ae92b1db.mp4

I was writing a more complex component than this where the operator was in a while statement in a function.

### Steps to Reproduce

Try formatting this using the latest version:
```astro
---
if (0 < 1) {

}
---

<h1>test!</h1>
```

**Comment by Princesseuh** [comment]
Oh! Nice find, that's weird. I'll take a look, thank you for the report (and the video!)
