### ISSUE TITLE
🐛 BUG: Module "<some component>.astro" has no default export despite project actually building.

### ISSUE THREAD

**Issue by henry-lang** [withastro/language-tools#350]
### Describe the Bug

I have a normal astro component called Navbar, and when importing like so from a layout:
`import Navbar from "../components/Navbar.astro"`

It gives me the error: Module '"<project>/src/components/Navbar.astro"' has no default export, despite the navbar having a jsx output, and the component actually building despite the language server error.

Navbar component:
```ts
---
import logo from '/logo.svg'
import github from '/github.svg'

const links: { text: string, href: string }[] = [
    { text: 'home', href: '/' },
    { text: 'featured', href: '/featured' },
    { text: 'about', href: '/about' },
]

const githubRepo = "";

let path = Astro.canonicalURL.pathname

if (path.endsWith('/') && path.length > 1) {
    path = path.substring(0, path.length - 1)
}
---

<style lang="scss">
    @use "../styles/variables.scss" as *;
    @use "../styles/mixins.scss";

    .nav {
        background-color: $mg;
        display: flex;
        justify-content: space-between;

        padding: {
            top: 1rem;
            bottom: 1rem;
            left: 1.5rem;
            right: 1.5rem;
        }

        * {
            display: flex;
            align-items: center;
        }
    }

    .logo {
        display: block;
        height: 2.5rem;
        padding-right: 0.5rem;
    }

    .link {
        @include mixins.accent_on_hover;

        font-size: 15pt;
        color: $fg;
        display: block;
        text-decoration: none;
        margin-left: 1rem;
    }

    .github {
        @include mixins.color_to_filter($fg);

        display: block;
        height: 1.5rem;

        &:hover,
        &:focus {
            @include mixins.color_to_filter($accent);
        }
    }
</style>

<nav class="nav">
    <div>
        <img alt="Soundbites waveform logo" class="logo" src={logo}>
        {links.map(link => <a class="link" href={link.href}>{link.text}</a>)}
    </div>

    <a href={githubRepo}><img alt="Github link logo" class="github" src={github}></a>
</nav>
```

### Steps to Reproduce

1. Create an astro project with no template - I just manually set it up using astro.config.ts
2. Create component like the one listed above
3. Import it in a layout
4. Make sure Astro language server is turned on in VSCode
5. Get the error that there is no default export.

**Comment by Princesseuh** [comment]
This is a false positive that happens whenever the language server can't parse the Astro file correctly due to flaws in the current parser

Luckily, we're in the process to migrate to a new parser which should fix this issue (and many more!). It's not quite ready yet, unfortunately, but hopefully will be soon

Thank you for submitting this issue!

**Comment by henry-lang** [comment]
Thank you for the response!

**Comment by martijnvdbrug** [comment]
I've come across this issue a few times, and every time it has been an issue in the script of the Vue file that is being imported. Can't pinpoint it exactly, but with the most recent case, this was the issue:

```diff
- function getProductById(id: string) {
-  return props.products.find((p) => p.id == id);
- }
+ const getProductById = (id: string) => props.products.find((p) => p.id == id);
```
