### ISSUE TITLE
🐛 BUG: Typescript type narrowing works in some places, but not others

### ISSUE THREAD

**Issue by henry-lang** [withastro/language-tools#351]
### Describe the Bug

In a component [name].astro:
```ts
---
import RelatedArticles from '../../layouts/RelatedArticles.astro';

export const getStaticPaths = (): { params: { name: string } }[] => {
    return [{ params: { name: 'cool' } }, { params: { name: 'epic' } }]
}


let { name } = Astro.params
if (typeof name != 'string') { name = '' }
---

<RelatedArticles relatedTo={name} predicate={(post)=> post.content.tags.includes(name)} />
```

The variable `name` is originally a string | number | undefined, so I ensure it's a string in the line after.
In the line of templating at the end, the use of name in the relatedTo field works resolves the type correctly:
<img width="471" alt="Screen Shot 2022-07-26 at 17 29 54" src="https://user-images.githubusercontent.com/24507488/181115558-3cf77c50-a843-4512-9fdd-d20aa2724f98.png">

However, in the second use of it in the predicate, it doesn't work for some reason:
<img width="968" alt="Screen Shot 2022-07-26 at 17 30 18" src="https://user-images.githubusercontent.com/24507488/181115620-7169ffcd-f29a-4550-a044-1a395ba89e9e.png">

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Use a component like the one above that takes in an arrow function that uses a type narrowed variable.
5. Type error!

**Comment by Princesseuh** [comment]
Thank you for filling this issue! Unfortunately, this is not on us. This [is normal TypeScript behaviour](https://www.typescriptlang.org/play?#code/DYUwLgBAFizA9gLggZzAJwJYDsDmEAfCbAVwFsAjEdQiE7AExADMcQGAoTZiACjACeABxDweMOPAgBCALwQARGix4FASggBvDhGiwEEeQoUcAvhw4SEHAPQ2IAPQD8FgMbxsaCGCg5883iF4NA1ZAD4IILQAOndsMBB46LAAQ1wUaJxXYBImFF4reDVbe10y8orKquqaiucOIA)

<img width="742" alt="image" src="https://user-images.githubusercontent.com/3019731/181145088-a29fe625-1647-40c3-a57d-0946afa1fd4c.png">
