### ISSUE TITLE
🐛 BUG: Syntax shows errors with code tag

### ISSUE THREAD

**Issue by torn4dom4n** [withastro/language-tools#360]
### Describe the Bug

I set `<code is:raw>` but this still shows errors.

![image](https://user-images.githubusercontent.com/27698189/182348473-6767f759-25b4-4050-9d1a-c76595a8e83d.png)

### Steps to Reproduce

1. Run `git clone https://github.com/AREA44/astro-stylegan3`
2. Open `src/index.astro`

**Comment by Princesseuh** [comment]
Thank you for creating this issue! However, it's a duplicate of https://github.com/withastro/language-tools/issues/285 so I'll close in favor of that one 😀
