### ISSUE TITLE
💡 RFC: Add support for TailwindCSS formatting in VSCode Extension

### ISSUE THREAD

**Issue by matthew-jones-uk** [withastro/language-tools#372]
### Background & Motivation

The TailwindCSS VSCode extension [recommends that their extension handles CSS formatting](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss#:~:text=Recommended%20VS%20Code%20Settings). This solves issues like [this](https://github.com/tailwindlabs/tailwindcss/discussions/6284) where VSCode auto formats and breaks functionality.

This approach won't work when setting `<style>` in `.astro` files, but I don't want to switch to the Tailwind extension for all formatting for this type, as it won't format the majority.

### Possible solutions
Ability to set a CSS formatter via setting.
### Alternatives considered
Explicit support for the aforementioned bug.

I guess as an alternative that won't include this extension is to use `prettier` for everything but I'm not sure if this would solve it?
### Risks, downsides, and/or tradeoffs
Not sure on the complexity.
### Open Questions
Not sure for now.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Hello! Thank you for creating this issue. I don't really get what you mean however as the Tailwind VS Code extension does not format files 😅

We're currently planning to switch the extension to use Prettier exclusively and the Tailwind Prettier plugin will soon be compatible  with Astro (just waiting for them to press Release, really) so, this should nonetheless fix this situation!
