### ISSUE TITLE
🐛 BUG: red flags ld+json script type (inline)

### ISSUE THREAD

**Issue by murtuzaalisurti** [withastro/language-tools#428]
### Describe the Bug

The extension red flags the use of ld+json script type and does not lint it correctly!

![Code_2Wfc2T7xL8](https://user-images.githubusercontent.com/68743212/194697379-afa31023-80af-4e4f-897c-d2caf6796adc.jpg)

### Steps to Reproduce

Use "application/ld+json" script type and write structured json data inside it. 
Write the script tag in an astro component or layout.

**Comment by Princesseuh** [comment]
Hello! This will be fixed by https://github.com/withastro/language-tools/pull/335, keeping the issue open until then

**Comment by murtuzaalisurti** [comment]
okay, thanks!

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/language-tools/pull/335
