### ISSUE TITLE
🐛 BUG: VSCode's `Organize Imports` command breaks `<script>` tags in `.astro` files

### ISSUE THREAD

**Issue by yegor-usoltsev** [withastro/language-tools#433]
### Describe the Bug

VSCode's `Organize Imports` command breaks `<script>` tags in `.astro` files.

For some reason `<script></script>` has been replaced with `<script>export { };` which leads to further compilation errors.

### Steps to Reproduce

1. Run `npm create astro@latest -- --template minimal`

2. Open project in Visual Studio Code, make sure [Astro Extension](https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode) is installed and enabled

3. Add `<script></script>` tag to `src/pages/index.astro` file:

```diff
---
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
+		<script></script>
	</head>
	<body>
		<h1>Astro</h1>
	</body>
</html>
```

4. Run `Organize Imports` command (<kbd>⇧</kbd><kbd>⌘</kbd><kbd>P</kbd> on macOS, type "Organize Imports", press <kbd>return</kbd>)

5. Expected no changes in the file, but got an invalid html:

```diff
---
---

<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<title>Astro</title>
-		<script></script>
+		<script>export { };
+
	</head>
	<body>
		<h1>Astro</h1>
	</body>
</html>
```

```shell
$ npm run build

> @example/minimal@0.0.1 build
> astro build

12:32:47 AM [build] output target: static
12:32:47 AM [build] Collecting build info...
12:32:47 AM [build] Completed in 3ms.
12:32:47 AM [build] Building static entrypoints...
Unexpected character in scriptData: 
12:32:47 AM [build] Completed in 233ms.

 building client 
[vite:esbuild] Transform failed with 1 error:
/sandbox/my-astro-site/src/pages/index.astro?astro&type=script&index=0&lang.ts:3:2: ERROR: Unexpected "/"
file: /sandbox/my-astro-site/src/pages/index.astro?astro&type=script&index=0&lang.ts:3:2

Unexpected "/"
1  |  export { };
2  |  
3  |    </head>
   |    ^
4  |    <body>
5  |            <h1>Astro</h1>
```

OS: macOS 12.6 (M1 Pro)
Node version: v16.17.1
VSCode version: 1.72.2
Astro version: 1.5.1
Astro Extension version: v0.27.0

**Comment by Princesseuh** [comment]
Aah, thank you for this reproduction, someone reported this a long time ago and we couldn't reproduce it consistently, this is really helpful.

I believe this is caused by the script tag being a single line. Will take a deeper look as soon as possible!
