### ISSUE TITLE
🐛 BUG: Less than (`<`) followed by a string starting with "link" or "meta" inside a script tag causes TypeScript bug

### ISSUE THREAD

**Issue by MarcusOtter** [withastro/language-tools#441]
### Describe the Bug

Bit of an obscure one, I'll try to explain it as good as I can. Sorry for the mouthful in the title.

Here's the problem (I think, see my highlight): 
![image](https://user-images.githubusercontent.com/35617441/197888183-cdc7e932-5230-4125-a524-d36791718ddb.png)
![image](https://user-images.githubusercontent.com/35617441/197887443-86de795b-ce4b-4975-95a8-5cccc21834a0.png)

The parser seems to expect me to close the "link tag" it picked up on. It It also works with anything starting with the word "meta", but not other tags like "body" or "section". I thought it was all elements that could exist in a header (such as `meta` and `link`) but it does not work, for example, with `title`.

The string after the `<` only needs to start with a keyword, any characters after it is still giving the error. So `... < alink` is not a problem, but `... < links.length` is a problem (which is how I ran into it).

### Steps to Reproduce

1. https://astro.new and select "Just the basics" in gitpod, for example
2. Go to `Layout.astro` and paste this script tag on line 20 after the `<slot/>`
	```html
	<script>
		const links = 10;
		for (let i = 0; i < links; i++) {
			console.log(i);
		}
	</script>
	```
3. See error on line 26.
4. Expecting to not get this error. Also get the error with variable names starting with "meta", but not with "title".

**Comment by Princesseuh** [comment]
This happens because our logic for closing tags is faulty, this will be fixed by [the new TSX output](https://github.com/withastro/language-tools/pull/335)

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/language-tools/pull/335
