### ISSUE TITLE
Causing weird visible glitches on the code between the fence (---)

### ISSUE THREAD

**Issue by aamirbinabd** [withastro/language-tools#444]
Type: <b>Bug</b>

Was working fine until earlier today and then suddenly I could see the code between the fence (---) blinking quickly and weirdly.

Steps:
1. Open a file with code between the dashes ---
2. Hit CTRL + S

Other note:
When I try to reload the Vscode window, it shows me a dialog with the note: "Are you sure you want to reload window? 'Organize imports' is in progress".

Extension version: 0.28.2
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 3244)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|7.63GB (4.37GB free)|
|Process Argv|--unity-launch --crash-reporter-id b42cf334-f29c-46f8-a1c1-1d2cf300ecb3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin|
|XDG_CURRENT_DESKTOP|zorin:GNOME|
|XDG_SESSION_DESKTOP|zorin|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30602634
iaj6b796:30602301
dbltrim-noruby:30604474

```

</details>

**Comment by aamirbinabd** [comment]
Update:

I removed `"source.organizeImports"` from `"editor.codeActionsOnSave": ["source.fixAll"]` and the glitch seems to fixed. 

Tried this after looking at a similar issue here: #443

**Comment by aamirbinabd** [comment]
This seems to be a bug with Vscode itself: [#165326](https://github.com/microsoft/vscode/issues/165326#issue-1434357747)

**Comment by Princesseuh** [comment]
VS Code 1.73.1 was released with a fix for this. Thank you to everyone who reported this issue!
