### ISSUE TITLE
🐛 BUG: TS Error when using HTML Components

### ISSUE THREAD

**Issue by dev-nicolaos** [withastro/language-tools#447]
### Describe the Bug

When using a pure [HTML component in an Astro template](https://docs.astro.build/en/core-concepts/astro-components/#html-components), Typescript throws the following error:

```bash
path/to/template.astro:12:4 Error: Component 'MyComponent' is not a valid component.

If this is a Svelte or Vue component, it might have a syntax error that makes it impossible to parse.
11  <body>
12    <MyComponent />
       ~~~~~~~~~~~
13  </body>
```

I believe this is an issue with the language tools rather than the compiler since this renders correctly with no errors or warnings.

TS reports the error both when running `astro check` and in the VS Code UI with the Astro extension installed.

## Environment

Astro version: 1.6.8
VS Code extension version: 0.28.2
OS: Windows 11 2022H2

### Steps to Reproduce

1. Create a _package.json_ with the contents:
```json
{
  "scripts": {
    "check:astro": "astro check",
    "start": "astro dev"
  },
  "devDependencies": {
    "astro": "^1.6.8"
  }
}
```
2. Create _src/components/myComponent.html_ with the contents: `<div>Hello world</div>`
3. Create _src/pages/index.astro_ with the contents:
```astro
---
import MyComponent from "../components/myComponent.html";
---

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <MyComponent />
</body>
</html>
```
4. If in VS Code, observe the error squiggle on line 12 of _index.astro_
5. Run `npm run check:astro"
6. Observe that a TS error is reported
7. Run `npm start`
8. Observe that the site builds successfully with no errors and "Hello world" can be seen when visiting the site root in the browser.

**Comment by nateemerson** [comment]
With a cursory grep I found this bit that might be a hint. Might have to do w/ being considered a JSX element...? https://github.com/withastro/language-tools/blob/d27d03a6fb8af910aae31f5e78f3a3d37f2165b2/packages/language-server/src/plugins/typescript/features/DiagnosticsProvider.ts#L274
