### ISSUE TITLE
💡 RFC: Ignoring specific folder or files

### ISSUE THREAD

**Issue by rikusen0335** [withastro/language-tools#449]
### Background & Motivation

So there's `Local History` extension in VSCode which make a local duplicate to safely save work by typing Ctrl+C, and astro language tool take it like
![スクリーンショット 2022-11-16 18 45 45](https://user-images.githubusercontent.com/19174234/202146406-38d2ca5d-c38a-4df0-9ed1-afb9fb054b25.png)

Now I wanted to, simply, ignore spefic folder or file like `.gitignore` do.

### Possible solutions
Make a option called like `astro.ignorePath` so that we can set it:
`"astro.ignorePath": [".history", "node_modules"]`

### Alternatives considered
Nothing.

### Risks, downsides, and/or tradeoffs
This shouldn't affect to any

### Open Questions
Nothing

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Hey, you can use the `exclude` field in your `tsconfig.json` for this.

**Comment by rikusen0335** [comment]
@Princesseuh I confirm it does work, I have to look for that. Thank you so much though!
