### ISSUE TITLE
🐛 BUG: Tailwind CSS prettier plugin doesn't work

### ISSUE THREAD

**Issue by chungweileong94** [withastro/language-tools#458]
### Describe the Bug

I was trying to set up the `prettier-plugin-tailwindcss` to work with the `*.astro` formatter, however, everything prettier config seems to work correctly except for `prettier-plugin-tailwindcss`, none of the tailwindcss classes is being formatted.

Here's my prettier config file `.prettierrc.cjs`:
```js
/** @type {import('prettier').Config} */
module.exports = {
  arrowParens: 'always',
  bracketSpacing: false,
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  bracketSameLine: false,
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  useTabs: false,
  plugins: [
    require.resolve('prettier-plugin-astro'),
    require.resolve('prettier-plugin-tailwindcss'),
  ],
};

```

### Steps to Reproduce

1. Create an Astro project (I'm using `pnpm`)
2. Install prettier-related packages, `pnpm add -D prettier prettier-plugin-astro  prettier-plugin-tailwindcss`
3. Create prettier config file, can refer to the config file above.
4. Try to format some tailwindcss classes.

**Comment by Princesseuh** [comment]
Hello, this was fixed in https://github.com/withastro/language-tools/pull/454 but it hasn't been released yet (was on holiday!)

I'm hoping to get a new version out soon-ish with this fix

**Comment by chungweileong94** [comment]
Cool, good to know that!
