### ISSUE TITLE
💡 RFC: Master CSS Language Service doesn't work

### ISSUE THREAD

**Issue by 1aron** [withastro/language-tools#459]
### Background & Motivation

Hi Astro Team:

I'm the creator of [Master CSS](https://css.master.co/). I'm [integrating Master CSS with Astro](https://github.com/master-co/css/tree/beta/examples/astro) and I'm running into an issue that seems to be with the Astro Language Service.

The textmate scopes aren't complete enough. It's broadly defined as `tag.any.*`.

<img width="1105" alt="Xnapper-2022-12-22-21 59 39" src="https://user-images.githubusercontent.com/33840671/209150524-69a9c493-0f18-4c47-9bb3-4ecf3f31eb3d.png">

[Master CSS Language Service](https://marketplace.visualstudio.com/items?itemName=masterco.master-css-language-service) doesn't work well with syntax highlighting based on the Astro Language Service.

### Proposed Solution

For native HTML, the scope of class names is: `meta.attribute.class.html`

<img width="1004" alt="Xnapper-2022-12-22-22 03 30" src="https://user-images.githubusercontent.com/33840671/209150989-a1cc5d55-c631-441d-a043-96534eedc4c7.png">

Svelte does this too, so the syntactic effect with Master CSS would be:

<img width="1094" alt="Xnapper-2022-12-22-22 00 30" src="https://user-images.githubusercontent.com/33840671/209150684-14b762f8-ccc4-47fc-9bbe-4bdb61650a04.png">

Master CSS uses syntax highlighting to solve the visual effect of redundant class names to improve readability.

We also hope to improve the DX writing Master CSS language in Astro.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [x] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Thank you for reporting this! I'll see what I can do.
