### ISSUE TITLE
🐛 BUG: "Could not find a declaration file for module" when using Workspaces and TypeScript Project References

### ISSUE THREAD

**Issue by WesSouza** [withastro/language-tools#462]
### Describe the Bug

I am using PNPM workspaces, TypeScript with Project References and VSCode.

My project builds fine (TypeScript compiles without any errors), but VSCode has issues finding type definitions for some of my own packages, even after they are built.

When I disable the Astro extension, the problem goes away.

For example:

1. `packages/mypub/src/index.ts` exports `MyPub`
2. `packages/mypub/package.json` package is named `mypub`
3. `packages/mypub/tsconfig.json` defines `compilerOptions.composite` as true
4. `packages/fastify/tsconfig.json` defines `references` as `[{ "path": "../mypub" }]`
5. `packages/fastify/src/myPubPlugin.ts` imports `import { MyPub } from "mypub";`

VSCode says:

```
Could not find a declaration file for module 'mypub'. '/Users/wes/Developer/MyPub/packages/mypub/dist/index.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mypub` if it exists or add a new declaration (.d.ts) file containing `declare module 'mypub';`ts(7016)
```

Here's a video showing the problem:

https://user-images.githubusercontent.com/126160/209738002-b046b397-392f-4b86-8935-4613410621d9.mov

But TypeScript checks and compiles it fine.

The full source files are on GitHub:
- [packages/mypub](https://github.com/WesSouza/MyPub/tree/main/packages/mypub)
- [packages/fastify](https://github.com/WesSouza/MyPub/tree/main/packages/fastify)

I'm going insane, what did I do that broke VSCode?

### Steps to Reproduce

1. Clone https://github.com/WesSouza/MyPub/ (run `pnpm install`)
2. Enable the Astro extension
3. Open `packages/fastify/src/myPubPlugin.ts`
4. Observe `"mypub"` has a TypeScript problem
5. Disable the Astro extension
6. Problem goes away

**Comment by Princesseuh** [comment]
Hello! Thank you for reporting this issue. Does this situation still happens when using the 0.29.0 pre-release?

(You can switch to it by pressing the "Switch to Pre-Release" button on the extension page in your editor)

**Comment by Princesseuh** [comment]
Tested myself and this is fixed in the current pre-release! 🥳

We're hoping to make the Pre-Release the default soon, sorry for the inconvenience in the meantime!
