### ISSUE TITLE
💡 RFC: Allow breakpoints in .astro files

### ISSUE THREAD

**Issue by Vap0r1ze** [withastro/language-tools#468]
### Background & Motivation

Using vitejs/vite#11576 and withastro/compiler#680, I'm able to use `debugger;` statements in frontmatter flawlessly.
![Code_4quUaJQw11](https://user-images.githubusercontent.com/20448879/210857945-cb15b59d-9d8e-4e35-8c31-046df50adc35.png)

The only missing piece of this puzzle now is the ability to create breakpoints in `.astro` files. I'm opening this issue here because I assume it's up to the LSP / extension to declare that the file can have breakpoints, and what lines/columns to allow them.

### Proposed Solution

Allowing breakpoints in `.astro` files

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Fair request! I think this is actually easy to add, just need to add the `breakpoints` field to the extension's package.json.

If you're interested in doing the PR, go ahead! Otherwise I'll take a look at it tomorrow 9AM (currently 22 in my timezone at the time of writing)
