### ISSUE TITLE
🐛 bug(vscode): astro commands shows when not in astro files

### ISSUE THREAD

**Issue by juliusmarminge** [withastro/language-tools#477]
### Describe the Bug

Most plugins, e.g. TypeScript only shows their "commands" if you're in a file or project which uses it - so the `TypeScript: Restart TypeScript server` only shows if I `CMD+SHIFT+P` in TypeScript files. This is nice since you only get relevant results when I search for the `restart` command.

![CleanShot 2023-01-22 at 12 22 17@2x](https://user-images.githubusercontent.com/51714798/213913243-ffaa2bd9-3371-46b2-8192-d71058754320.png)

However, this is not how Astro works. You get the `restart astro language server` no matter what file im browsing - so if I recently used the command it gets chosen even when im no longer in astro - if that makes sense... this is just "annoying" and "slows" down developers as we want to restart our TS servers quite "often".

![CleanShot 2023-01-22 at 12 24 24@2x](https://user-images.githubusercontent.com/51714798/213913272-1626eff9-ebdd-4bca-bb85-bdc09f729c7c.png)

> Note: I get that this is quite "nit" but it's still an annoying thing to have. The plugins commands doesn't need to show up when I'm not browsing Astro files.

### Steps to Reproduce

1. In any VSCode project, Restart the Astro language server by `CMD+shift+P` then type `restart` and select the astro one. (note that astro is the only one showing up (well you might have other plugins but at least the TS option doesn't show))
2. Later, when you're in a normal TS project, you want to restart the typescript server you do the same process - and muscle memory just does it without thinking, however, the Astro option will be chosen even though you're not in an Astro file =>> you have to do the process again and look what server you're restarting

**Comment by Princesseuh** [comment]
Thank you for reporting this! This is easy to fix, using the `when` clause documented here: <https://code.visualstudio.com/api/references/when-clause-contexts>

All of the commands could be only shown when on an Astro file, that seems definitely fair to me. If anyone is interested in tackling these, go ahead, otherwise I'll take a look as soon as possible myself
