### ISSUE TITLE
BUG: npm run build fails: cannot find named export from nostr-tools package 

### ISSUE THREAD

**Issue by salimp2009** [withastro/language-tools#486]
### Describe the Bug

Hi, 
I installed nostr-tools package using npm 
https://www.npmjs.com/package/nostr-tools

then I used named imports in an .astro file under /pages 
like below and several others
`import { nip19 } from "nostr-tools";`
when I use 
`npm run dev `; it works
by when I run `npm run build `then I get this error (both during the deploy and also local run)
```
Named export 'nip19' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
 CommonJS modules can always be imported via the default export, for example using:
import pkg from 'nostr-tools';
const { nip19, relayInit } = pkg;
```
I also checked npm and nostr-tools source repo , the package exports nip19 and all other ones I used;
https://www.npmjs.com/package/nostr-tools
https://github.com/nbd-wtf/nostr-tools

And even if I use recommended via default export, both npm run dev and build works but language server shows a false error 
Module "...." has default export. ( I am using astro-language-server 0.29.6) in nvim
my  source code is also available at 
https://github.com/salimp2009/astro_tutorial/blob/main/src/pages/notes.astro

### Steps to Reproduce

1. `npm create astro@latest` 
2.  `npm i nostr-tools`
3. add `import { nip19 } from "nostr-tools" `in index.astro

```
const pubKeyhex= nip19.decode(
  "npub1sadasdasdasdadadasd"
).data;
```

4. `npm run dev` (works OK)
5. `npm run build` (fails)
6. Error: 
```
Named export 'nip19' not found. The requested module 'nostr-tools' is a CommonJS module, which may not support all module.exports as named exports.
 CommonJS modules can always be imported via the default export, for example using:
import pkg from 'nostr-tools';
const { nip19, relayInit } = pkg;
```
8. Expected: builds OK.

My source code is also on github
https://github.com/salimp2009/astro_tutorial/blob/main/src/pages/notes.astro

**Comment by Princesseuh** [comment]
Hello!

This is not an issue with the language server. You probably need `allowSyntheticDefaultImports` in your `tsconfig.json` for the default import to show no errors.

**Comment by salimp2009** [comment]
ok only I think default export method showing false error part is related to language server ? 
but you are right, the rest is related to build failing; 
so I should just report this to general astro repo because the main problem is the build fails although the package allows named imports.

**Comment by Princesseuh** [comment]
Yes, you can report the build failing on the main repo. I suspect the package is badly packaged for ESM usage...
