### ISSUE TITLE
Saving a new file causes long delay and hangs the editor. 

### ISSUE THREAD

**Issue by aamirbinabd** [withastro/language-tools#488]
Type: <b>Bug</b>

1. Create a new file inside Astro project (usually src folder).
2. Save the file (ctrl + s).

Shows [Saving 'Test.astro': Getting code actions from ''Astro''].

Extension version: 0.28.2
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.15.0-60-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz (4 x 2199)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 4, 2|
|Memory (System)|7.63GB (1.45GB free)|
|Process Argv|--unity-launch --crash-reporter-id b42cf334-f29c-46f8-a1c1-1d2cf300ecb3|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|zorin|
|XDG_CURRENT_DESKTOP|zorin:GNOME|
|XDG_SESSION_DESKTOP|zorin|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30669237
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
vscrpc:30673769
pythonsymbol12:30671437
funwalk2:30676043
pythonms35cf:30676801

```

</details>

**Comment by Princesseuh** [comment]
Hello! Thank you for reporting this issue. This often happens when the workspace is too big and the extension tries to load a lot of files. How big is your workspace?

**Comment by aamirbinabd** [comment]
Quite large, with at least 100 files in the src folder. What is the workaround for it?

**Comment by Princesseuh** [comment]
Hmm, that's not that much files, it shouldn't cause a problem.

Could you show your `tsconfig.json`?

**Comment by aamirbinabd** [comment]
**tsconfig.json**
```
{
  "compilerOptions": {
    // Enable top-level await, and other modern ESM features.
    "target": "ESNext",
    "module": "ESNext",
    // Enable node-style module resolution, for things like npm package imports.
    "moduleResolution": "node",
    // Enable JSON imports.
    "resolveJsonModule": true,
    // Enable stricter transpilation for better output.
    "isolatedModules": true,
    // Add type definitions for our Astro runtime.
    "types": ["astro/client"]
  }
}
```

And also:

**.vscode > settings.json**
```
{
  "htmltagwrap.tag": "div",

  "editor.codeActionsOnSave": ["source.fixAll", "source.organizeImports"],
  "livePreview.defaultPreviewPath": "/home/aamir/Documents/Github/techboxx-macrosite/dist/index.html"
}
```

**Comment by Princesseuh** [comment]
Hmm, unfortunately I'm not too sure what to say. As I said, this issue is usually caused by too many files at once or very complex dependencies, but I believe your project should be fine.

We're always looking towards improving performance, but I'm unfortunately fairly busy with other parts of Astro at the moment and can't really take a good look at it.

In the meantime, disabling code actions `astro.typescript.codeActions.enabled` and formatting on save can help you out, the latter you could do through the Prettier extension instead.

**Comment by aamirbinabd** [comment]
Thank you for your input. I'm looking forward to the upcoming improvements.
