### ISSUE TITLE
🐛 BUG: `workspace/didChangeWatchedFiles` capability is not being registered on the `astro-ls` server

### ISSUE THREAD

**Issue by Odas0R** [withastro/language-tools#489]
### Describe the Bug

The event `workspace/didChangeWatchedFiles` is needed so that it's possible to watch for file changes across the workspace. Whenever I change a `.ts` file it doesn't propagate those changes (types) on `.astro` files when using the [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#astro).

There was a [PR](https://github.com/neovim/neovim/pull/22405) recently merged into the neovim codebase that implements this event.

I also filled an [issue](https://github.com/neovim/nvim-lspconfig/issues/2467#issuecomment-1455214398) on the `nvim-lspconfig` repo with this problem.

### Steps to Reproduce

no steps to reproduce.

**Comment by Princesseuh** [comment]
To be more clear, is the issue that the watchers are not dynamically registered on the client by the server when available? I'm not sure how you're supposed to register the `workspace/didChangeWatchedFiles` capability on the server.

**Comment by Odas0R** [comment]
> To be more clear, is the issue that the watchers are not dynamically registered on the client by the server when available? I'm not sure how you're supposed to register the `workspace/didChangeWatchedFiles` capability on the server.
> 
> At the moment, the server expects the client to setup the watchers, ex for VS Code:
> 
> https://github.com/withastro/language-tools/blob/94bc851d4cebd281eb5b0fa17f4c1fa711a268e9/packages/vscode/src/shared.ts#L35

Well I'm not 100% sure :')


From the [nvim-lsp issue](https://github.com/neovim/nvim-lspconfig/issues/2467#issuecomment-1455214398)
> From a quick look at the source code for Astro, I can see where it [consumes the notifications](https://github.com/withastro/language-tools/blob/94bc851d4cebd281eb5b0fa17f4c1fa711a268e9/packages/language-server/src/server.ts#L216), but I don't see where it sends the request to register the capability.

From another [issue](https://github.com/neovim/neovim/issues/16078)

> **Feature description**
> The watched files notification is sent from the client to the server when the client detects changes to files and folders watched by the language client (note although the name suggest that only file events are sent it is about file system events which include folders as well). It is recommended that servers register for these file system events using the registration mechanism. In former implementations clients pushed file events without the server actively asking for it.

https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_willRenameFiles

## My Issue

Changes on `.ts` files don't propagate to `.astro` files. I haven't put a lot of time into it, to figure out the issue or even try to create my own fix, but since I need to work I go with what I have :laughing:.

I submitted this issue on the `nvim-lsp-config` repo that led me here. Wonder if there are any ideas on what this could be since I got no accurate understanding of this topic.

**Comment by t-ober** [comment]
@Odas0R : I am still facing the same issue. Have you ever found a way to resolve it?

**Comment by Odas0R** [comment]
> @Odas0R : I am still facing the same issue. Have you ever found a way to resolve it?

I've tried right now and with:

Packages:

```
"astro": "^4.0.7",
"typescript": "^5.3.3",
"@astrojs/language-server": "^2.5.5"
```

**Note:** You'll need to install typescript on every Astro project so the lsp can find the ts binary.

Neovim:

```
NVIM v0.10.0-dev-1204+gd1bc6fca7
Build type: RelWithDebInfo
LuaJIT 2.1.1695409640
Run "nvim -V1 -v" for more info
```

It's working, I'm going to close this.
