### ISSUE TITLE
🐛 BUG: LSP Fails to Parse Markdown Files (Neovim)

### ISSUE THREAD

**Issue by harrisoncramer** [withastro/language-tools#495]
### Describe the Bug

I'm using Neovim and have installed Astro's LSP and configured it correctly. It understands and parses `.astro` files fine. However, it cannot parse `.md` files. It seems to be thrown off by the frontmatter.

![Screenshot 2023-03-18 at 3 47 29 PM](https://user-images.githubusercontent.com/32515581/226134161-2a4dc3f1-a61c-4a8a-a465-0941fc775049.png)

### Steps to Reproduce

1. Install and configure the Astro LSP (Version `0.29.6`). I'm using Mason and LspConfig. The LSP is working fine with Astro files.
2. `npm create astro@latest`
3. Use blog template
4. Typescript, yes, strict, install deps.
5.  Open up any of the preconfigured `.md` markdown files.

The LSP has attached to the buffer, and there are no errors from the language server:

![Screenshot 2023-03-18 at 3 49 28 PM](https://user-images.githubusercontent.com/32515581/226134238-4eae1c1b-3daf-4413-885f-13340e9059dc.png)

**Comment by Princesseuh** [comment]
Our LSP does not handle Markdown files in any way (and is not supposed to at this time). I'd recommend using a Markdown language server
