### ISSUE TITLE
🐛 BUG: VS Code "Rename Symbol" (F2) on inline js fails returning "Rename failed to apply edits"

### ISSUE THREAD

**Issue by igorkb** [withastro/language-tools#496]
### Describe the Bug

VSCode "Rename Symbol" doesn't work on inline scripts inside .astro files raising "Rename failed to apply edits".

"Rename Symbol" works as intended on external .js and .ts files and on inline scripts inside .html files. 

Using:
VS Code 1.76.2
Astro 2.1.5
Astro extension v0.28.2
No custom config. No other extensions.

![Trying to rename var x](https://user-images.githubusercontent.com/6250229/227224470-fcbbeb10-df8b-4a5d-bf9e-3c179a704a7f.jpg)

![Error](https://user-images.githubusercontent.com/6250229/227224522-abbb8120-315e-4fee-ad68-e50586514ee6.jpg)

### Steps to Reproduce

1. Download a portable version of VS Code and unzip it on a new folder.
2. On Windows, create a new folder called "data" inside the VS Code folder u just created so u can start fresh without any extension or custom settings.
3. Start VS Code and install the official astro extension.
4. Do a "npm create astro@latest". Use "empty" template. Install dependencies. Yes to TS. Relaxed TS. No to Git init.
5. Put the following code on index.astro:
`<script is: inline>
    let x = 1;
    x = 123;
</script>`
6. Put your cursor on x and press F2 (Rename Symbol). then type "y" and press Enter.
8. ERROR. Nothing changes and a notification is shown saying "Rename failed to apply edits".

(Updated to delete unnecessary steps and include images)

**Comment by thdoan** [comment]
Until they fix this, the silly workaround I've had to do is keep an open Untitled document open, set it to JavaScript format, and do all my edits there before pasting into the `.astro` file. It makes Astro development rather cumbersome.

**Comment by Princesseuh** [comment]
Does this work in the Pre-release version? We had several improvements to renaming in 0.29.4, and I believe this should work

**Comment by igorkb** [comment]
> 


> Does this work in the Pre-release version? We had several improvements to renaming in 0.29.4, and I believe this should work

Yes. It's working on the pre-release version. Thanks.

**Comment by Princesseuh** [comment]
Awesome, will close this issue then. We're hoping to release the pre-release soonish 😄

**Comment by igorkb** [comment]
Actually, it's not working OK. When renaming a variable on the frontmatter, it gets crazy.

![image](https://user-images.githubusercontent.com/6250229/232349522-9b5b80b6-2a44-4158-b1bd-b148a8b4e429.png)

**Comment by Princesseuh** [comment]
Hmm, that looks like a mapping issue, is it possible that you're on Windows and are as such affected by this issue? https://github.com/withastro/compiler/issues/714

**Comment by igorkb** [comment]
Well... I'm on Windows. I think it's possible, but I'm not sure.
