### ISSUE TITLE
🐛 BUG: Syntax highlighting glitch in VSCode extension

### ISSUE THREAD

**Issue by maddsua** [withastro/language-tools#498]
### Describe the Bug

Having a line, like shown in the picture, causes syntax highlighting to glitch further down the file:

![image](https://user-images.githubusercontent.com/102395937/229040544-c7e19847-d094-44a5-946a-986141b5b08e.png)

You can see JS keywords and other stuff just turned white.
Basically, having JSX syntax inside a JS snippet (or whatever it's called, I mean `{ some.js.code('here') }` snippet) causes this. The presence of a `map` function or that ternary operator does not make a difference. 

Looks like it's just a cosmetic issue, code completion seems to work fine.

VSCode version: 1.74.2
Astro extension version: 0.28.2

### Steps to Reproduce

1. Have a line like `{ <li>whatever</li> }` inside a template.
2. Syntax highlighting is successfully broken 🎉

**Comment by maddsua** [comment]
Oh, I just realized: It's because I "didn't" close a void tag! But still, I think it should support this edge case

**Comment by Princesseuh** [comment]
Unfortunately, there's no ways for us to fix this, we don't own the syntax inside JSX expressions (we use VS Code's) and JSX is sensible to closing void tags (it's invalid in JSX to not close them explicitly). Syntax highlighting is also rarely error tolerant, in general. 

It's very unlikely that we'll fix this, sorry!

**Comment by maddsua** [comment]
> Unfortunately, there's no ways for us to fix this, we don't own the syntax inside JSX expressions (we use VS Code's) and JSX is sensible to closing void tags (it's invalid in JSX to not close them explicitly). Syntax highlighting is also rarely error tolerant, in general.
> 
> It's very unlikely that we'll fix this, sorry!

Okay, got it, no problem! Maybe we should mention this somewhere on the docs?
