### ISSUE TITLE
🐛 BUG: `allowArbitraryAttributes` doesn't support alpine `.` modifiers

### ISSUE THREAD

**Issue by mikestopcontinues** [withastro/language-tools#500]
### Describe the Bug

The setting supports most alpine attributes, however the `.` character breaks the types... And the `.` is used for quite a lot!

Example: `x-on:click.outside="isOpen = false"`

Some docs:
https://alpinejs.dev/directives/on#keyboard-events
https://alpinejs.dev/directives/on#modifiers

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. `astro add alpinejs`
3. Add `x-on:click.outside="console.log('!')"` to an element
4. Error! You'll see an error message.

Even worse...
1. Add `x-on:click.outside="console.log('!')"` to an element _within a loop_.
2. Error! Syntax highlighting is completely broken.

Example:
```jsx
<div>
  {
    ['!'].map((str) => (
        <div 
          class="subMenu"
          x-data="{isOpen: false}" 
          x-on:click.outside="isOpen = false"
        >
          {str}
        </div>
      ))
  }
</div>
```

**Comment by mikestopcontinues** [comment]
That helps a lot. I just want to point out that within loops, it no longer breaks everything, but there's still a highlighting issue. Thanks!

<img width="484" alt="Screenshot 2023-04-04 at 2 00 46 PM" src="https://user-images.githubusercontent.com/150434/229799674-2e91b919-5c7b-4172-a286-5a58fb1ea43a.png">

**Comment by Princesseuh** [comment]
Ah yeah, that one is a bit challenging since we don't provide the highlighting inside JSX expressions ourselves..

**Comment by revnelson** [comment]
> Hello, this is not related to `allowArbitraryAttributes`. It's caused by the current version of the extension not being able to parse attributes with `.` in them as it is invalid in JSX.
> 
> You can try out the Pre-release version of the extension, it has a fix for this.

Where can I find the pre-release to try?

**Comment by Princesseuh** [comment]
The pre-release has been released many months ago, this should now work just fine in any recent versions!
