### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Frank-Mayer** [withastro/language-tools#501]
### Describe the Bug

Error message when opening a astro file in neovim:

```
Error executing vim.schedule lua callback: ...llar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: Cannot serialise function: type not supported
stack traceback:
        [C]: in function 'encode'
        ...llar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: in function 'notify'
        ...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:1326: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
LSP[id=2] client has shut down after sending Successfully initialized! 🚀
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein
```

My lspconfig for the Astro LS:

```lua
lspconfig["astro"].setup({
	capabilities = capabilities,
	on_attach = on_attach,
	settings = {
		astro = {
			cmd = { "astro-ls", "--stdio" },
			filetypes = { "astro" },
			init_options = {
				configuration = {},
				typescript = {
					serverPath = "",
				},
			},
			root_dir = lspconfig.util.root_pattern(
				"astro.config.mjs",
				"astro.config.js",
				"astro.config.cjs",
				"package.json"
			),
		},
	},
})
```

`:LspInfo` shows
```
Config: astro
  filetypes:         astro
  root directory:    /Users/frankmayer/Documents/Git/homepage
  cmd:               astro-ls --stdio
  cmd is executable: true
  autostart:         true
  custom handlers:
```

### Steps to Reproduce

1. cd into my project [`Frank-Mayer/homepage`](https://github.com/Frank-Mayer/homepage)
2. start `nvim`
3. Open a astro file (doesn't matter which file)
4. Error output in nvim (as described above)

**Comment by Frank-Mayer** [comment]
I tried updating to nvim 0.9.0, but there is no difference. I get the same error (except for the version number in the path).

**Comment by Princesseuh** [comment]
The language server changed a lot in the latest 2.0 release, so this error is probably not relevant anymore, since literally everything is done differently now.

Feel free to open another issue if it still happens!

**Comment by Frank-Mayer** [comment]
But how to configure the new version? Volar has no documentation at all on their website, and I could not find any documentation on this repository either.

**Comment by Princesseuh** [comment]
The only init option that's expected is `typescript.tsdk` to point to TypeScript's lib folder. I'm not familiar with Neovim too much, but I'd expect the rest to be fairly standard.

Tools like lspconfig have been updated already,  those might be neat resources to look at

**Comment by Frank-Mayer** [comment]
Thank you very much for the help 👍
