### ISSUE TITLE
🐛 BUG: Extension possibly conflicting with non-Astro project

### ISSUE THREAD

**Issue by nate-tb** [withastro/language-tools#507]
### Describe the Bug

Trying to commit code to a Git repository in a non-Astro app and the pre-commit checks are displaying this error (error TS6053: File 'astro/tsconfigs/base' not found) despite deleting the Astro extension (this first occurred when the Astro extension was installed):

```
*****/node_modules/.pnpm/ts-node@10.9.1_@swc+core@1.2.173_@types+node@18.14.2_typescript@4.7.3/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File 'astro/tsconfigs/base' not found.
```

Any idea why this would be happening?

### Steps to Reproduce

1. Making a Git commit with pre checks

**Comment by Princesseuh** [comment]
That file is only referred to in a tsconfig.json of an Astro project. 

Is it possible that you have an Astro project elsewhere that that other project could potentially loading by accident? Perhaps for instance, that the Astro project is higher up in the hierarchy and TypeScript is going up directories trying to find a tsconfig.json?

Either way, it definitely has nothing to do with the VS Code extension or Astro itself, like I said that file is only referred to through the standard way of doing so in TypeScript.

**Comment by nate-tb** [comment]
There was as file in the parent folder of my repo that specified the 'astro/tsconfigs/base' directory.  Once I deleted it, the problem was solved.  Hadn't had issues until we changed to a monorepo in the same directory.  Thanks for the assistance.
