### ISSUE TITLE
🐛 BUG: Semicolon in comment causes overflow (VSCode)

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/language-tools#510]
### Describe the Bug

A semi-colon as the last character in a comment on the final line of a component script causes some weird behavior and throws errors, if the last statement before does not end in a semi-colon.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/64310361/232535479-30c04f12-bc1f-4565-bbc1-a2f39c679ed4.png" alt="">
</details>

### Steps to Reproduce

1. Create a new page/component file
2. Use the following Astro code (the last statement in the component script must not end with a semi-colon. the final line must be a comment ending in a semi-colon (other content doesn't matter))
```astro
---
console.log('test')

// ;
---

<html lang="en">
	<head>
		<title>Astro bug repro</title>
	</head>
	<body>
	</body>
</html>
```
3. VSCode throws errors such as `Cannot find name 'html'/'lang'.`

**Comment by Princesseuh** [comment]
Is this using the pre-release or the normal version of the extension?

**Comment by TheOtterlord** [comment]
Ooh, I completely forgot about the prerelease. I've just had a look, and while it's fixed, another error is now appearing with the same code snippet (`Declaration or statement expected`). This time tied to the opening `---` on the first line.
![image](https://user-images.githubusercontent.com/64310361/232582481-0c6520fd-8c50-416b-9c94-227e73697ef2.png)

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/language-tools/pull/534
