### ISSUE TITLE
🐛 BUG: VS Code matching tag highlighting issue 

### ISSUE THREAD

**Issue by absktoday** [withastro/language-tools#511]
### Describe the Bug

Hi, I started to learn Astro and I am using VSCode as an IDE. I noticed that the matching tag highlighting is not working in VSCode is this know or desired?

Here I clicked on a div tag the VSCode highlights all the div tags instead of just highlighting the matching closing tag.
![image](https://user-images.githubusercontent.com/54511046/232972918-4777a83f-8da0-4083-9937-b8bb137d119e.png)

It is supposed to be like this I believe.
![image](https://user-images.githubusercontent.com/54511046/232973103-432b1213-a856-4083-acbb-4aba05807cff.png)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by Princesseuh** [comment]
Thank you for reporting this issue! I believe it's related to https://github.com/withastro/language-tools/issues/309

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/language-tools/pull/534
