### ISSUE TITLE
🐛 BUG: Syntax highlighting issue in VS Code

### ISSUE THREAD

**Issue by thdoan** [withastro/language-tools#512]
### Describe the Bug

This TypeScript code messes up the syntax highlighting in VS Code:

**test.astro**
```
---
---

<script>
function test(el: HTMLElement) {
  const html = el.innerHTML;
  const go = () => {
    (<HTMLElement>tag).innerHTML += '';

    if (n < html.length - 1) {
      // ...
    }
  };

  let n = 0;
  let tag: string | HTMLElement = '';
  go();
}
</script>
```

![image](https://user-images.githubusercontent.com/4110567/233760997-00f3ebac-2ac0-4bf2-985b-3232512b23bd.png)

My system:
Version: 1.77.3 (user setup)
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:02.548Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

I'm using Astro extension v0.28.2 (VS Code says it's up to date).

### Steps to Reproduce

1. Create a new .astro file in VS Code
2. Paste the code above
3. Error: syntax highlighting gets messed up

**Comment by Princesseuh** [comment]
[Casting types using the `<Type>` syntax is not supported in TSX and TSX-like (which is essentially what Astro files are) environnements](https://www.typescriptlang.org/docs/handbook/jsx.html#the-as-operator).

There's nothing we can do about this ourselves, we don't maintain the syntax used for TypeScript, VS Code does.

**Comment by thdoan** [comment]
@Princesseuh thanks for feedback. This is a satisfactory substitute:

```
tag = tag as HTMLElement;
tag.innerHTML += '';
```
