### ISSUE TITLE
🐛 Binding element 'paginate' implicitly has an 'any' type

### ISSUE THREAD

**Issue by thdoan** [withastro/language-tools#516]
### Describe the Bug

The line below results in a "Binding element 'paginate' implicitly has an 'any' type" error in VS Code:

```
export async function getStaticPaths({ paginate }) {
```

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Add the code above in VS Code
3. Error! The error above is produced

**Comment by Princesseuh** [comment]
This is normal, your function is not typed.

You probably want something like this
```ts
import { GetStaticPaths } from 'astro';

export const getStaticPaths = (async ({paginate}) => {
  return paginate(...)
}) satisfies GetStaticPaths;
```

**Comment by thdoan** [comment]
@Princesseuh thanks for the sample code!

FYI the code I used was copied from https://docs.astro.build/en/reference/api-reference/#paginate -- for people new to TypeScript maybe the docs should be updated to use your code sample instead.

**Comment by unapersona** [comment]
Currently, you can type the `getStaticPaths` parameter as `GetStaticPathsOptions`

```ts
import type {GetStaticPathsOptions} from "astro";

export async function getStaticPaths({paginate}: GetStaticPathsOptions){
  return paginate(...)
}

```
