### ISSUE TITLE
import type from astro file to typescript file

### ISSUE THREAD

**Issue by nirus** [withastro/language-tools#519]
### What version of `astro` are you using?

astro@2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I am unable to import the type declared in `.astro` file to `typescript` code in VScode editor. 

Below error is being displayed

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2213751/235432166-3227e1b9-577c-4721-9c0a-f588242baa54.png">

I upgraded the `package.json` using `yarn upgrade` to use latest packages. Still seeing the error shown in the screenshot.

I have attached the whole repo with the code and config settings.

### Link to Minimal Reproducible Example

https://github.com/nirus/cr-engine/blob/main/src/restapi/fetchAuthor.ts#L4

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by nirus** [comment]
is this fixed?

**Comment by Princesseuh** [comment]
> is this fixed?

Another unrelated fix for it will be released later today, which should hopefully fix all the issues.
