### ISSUE TITLE
🐛 BUG: Using fetch results in an error

### ISSUE THREAD

**Issue by matthewp** [withastro/language-tools#52]
### Describe the Bug

```astro
---
const data = await fetch("url")
// Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher
---
```

### Steps to Reproduce

1. Use `fetch` in the component script section.

**Comment by matthewp** [comment]
Thanks for finding all of these issues @RafidMuhymin ! Can you provide an example project where this occurs? I've been unable to recreate it myself.

**Comment by Princesseuh** [comment]
This shouldn't be an issue anymore since this commit https://github.com/withastro/language-tools/commit/65017573a4d8f585dc93ed1fac601c9e721d3f28 is it?

**Comment by matthewp** [comment]
Yep! Good point, thanks.
