### ISSUE TITLE
VSCode: CSS Modules Error

### ISSUE THREAD

**Issue by CommanderGL** [withastro/language-tools#546]
### Describe the Bug

When using the official Astro extension on VSCode when I import CSS Modules it throws error:
`Cannot find module '/path/to/example.module.css' or its corresponding type declarations.`

### Steps to Reproduce

1. Install VSCode Extension
2. Create Astro Project
3. Use Typescript
4. Use CSS Modules
5. Get Yelled At

**Comment by Princesseuh** [comment]
The language-server intentionally does not include definitions for CSS modules. If you followed Astro's installation, you should have a `env.d.ts` referring to the client types that includes definitions for CSS modules.

If it still doesn't work, please share a reproduction

**Comment by Princesseuh** [comment]
Closing due to lack of answer, I suspect your project was misconfigured.
