### ISSUE TITLE
🐛 BUG: Astro VS Code extension v2.0.13 causes asset imports to be considered of type string instead of ImageMetadata

### ISSUE THREAD

**Issue by cezarderevlean** [withastro/language-tools#557]
### Describe the Bug

Imported assets (from assets folder, experimental mode is on) are seen as strings, so TypeScript shows this error when trying to access `importedAsset.src`:

`Property 'src' does not exist on type 'string'. ts(2339)`

Using extension v2.0.13. 

Reverting to extension version v1.0.8 fixes the problem.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. import a file from `/src/assets`
3. attempt to access `importedFile.src`
5. TypeScript Error: `Property 'src' does not exist on type 'string'. ts(2339)`

Expected result: no typescript error.

<img width="789" alt="image" src="https://github.com/withastro/language-tools/assets/1387978/cf907cc6-3731-4713-a048-c7128d53d1e3">

**Comment by Princesseuh** [comment]
It's highly likely that the extension here is not wrong, but something in the project is overwriting the proper types. The previous version wrongly missed some types at times.

An easy way to test it is to see if you have the same types in `.ts` and `.astro` files, `.ts` being the one that's in the right.

I'll investigate to see if it's something in our types, and what we can do about it if so
