### ISSUE TITLE
🐛 BUG: Neovim can't load the astro ls

### ISSUE THREAD

**Issue by JaavierR** [withastro/language-tools#559]
### Describe the Bug

Error message when as soon as I open an astro file in neovim:

```
Error executing vim.schedule lua callback: ...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1309: RPC[Error] code_name = I
nternalError, message = "Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in undefined"
stack traceback:
        [C]: in function 'assert'
        ...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1309: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

My lspconfig for the astro ls is:

```lua
lspconfig.astro.setup({ capabilities = capabilities })
```

`:LspInfo` shows:

```
 Other clients that match the filetype: astro
 
 Config: astro
 	filetypes:         astro
 	root directory:    /Users/javier/Developer/personal/arrakis
 	cmd:               /Users/javier/.local/share/nvim/mason/bin/astro-ls --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

Finally, for the context I have installed typescript as a dev dependency in the astro project, Mason shows me that the current version of the astro-language-server installed is the v2.0.0 and my NVIM version is v0.9.1

### Steps to Reproduce

1. cd into the astro project
2. start `nvim`
3. open an astro file (doesn't matter which astro file)
4. Error output in nvim, the one described above

**Comment by Princesseuh** [comment]
You need to pass a path to `tsserverlibrary.js` through the `typescript.tsdk` init params.

**Comment by JaavierR** [comment]
@Princesseuh thanks for the clarification. Now it is working but as a note I had to point to the folder that contains the `tsserverlibrary.js` file as indicated in the PR that is referenced in this issue.

Now I have a doubt and it is that I had to reference the `tsserverlibrary.js` that I have installed globally, is there any way to take by default the one that is installed in the project as a dependency?

Once again thanks for the quick reply!

**Comment by intagaming** [comment]
Good news: it's been merged just before workday 😄

**Comment by JaavierR** [comment]
> Good news: it's been merged just before workday 😄

That was fast!

I downloaded the changes, but unfortunately if I don't specify the path to the typescript server folder that I have installed globally I get the same error that I commented at the beginning of the issue. What I was hoping was that it could take the path to the typescript server installed in the project similar to how 'Volar' currently does, since from what I read it shares similarities. 

Maybe it's due to some specific configuration of mine, but I'm not doing anything strange with the configuration and I made sure to have typescript installed as a dependency in the project. I don't know if there is any specific information beyond the error detail that I can provide to see the problem or if it is currently a limitation.

For context: 

The next snippet errors out as I mention above
```lua
lspconfig.astro.setup({
  init_options = {
    typescript = {}
  },
})
```

This snippet works as expected
```lua
lspconfig.astro.setup({
  init_options = {
    typescript = {
      tsdk = vim.fs.normalize('~/Library/pnpm/global/5/node_modules/typescript/lib')
    }
  },
})

```

**Comment by intagaming** [comment]
Same. Copying word-by-word the default config from lspconfig and it works fine. Removing them doesn't work. Not sure what's happening so I'll ask them.

**Comment by johnsoncodehk** [comment]
> is there any way to take by default the one that is installed in the project as a dependency?

You can try define `typescript.tsdk = 'node_modules/typescript/lib'`.

**Comment by intagaming** [comment]
So... update: The culprit was Mason + `mason-lspconfig`. Disabling it will have the default `nvim-lspconfig` config for Astro works. I'll see if I can figure out the workaround. I might ditch Mason entirely.

**Comment by intagaming** [comment]
Speaking of which... I think I found the exact thing to fix: https://github.com/williamboman/mason-lspconfig.nvim/blob/f0ce33f4794a2364eb08d09d09380e8b04ec5e6a/lua/mason-lspconfig/server_configurations/astro/init.lua#L6. Be right back.

**Comment by intagaming** [comment]
Yup, that fixed it. Update `mason-lspconfig` and test again?

**Comment by JaavierR** [comment]
> Yup, that fixed it. Update `mason-lspconfig` and test again?

Indeed, I upgraded and the problem disappeared. Now there is no need to specify the path to the typescript server folder (if that's what you want).

Thank you all for the quick follow up and help. I will close the issue since updating `nvim-lspconfig` and `mason-lspconfig` solved the problem.
