### ISSUE TITLE
💡 RFC: Support Svelte 4

### ISSUE THREAD

**Issue by ghostdevv** [withastro/language-tools#589]
### Background & Motivation

Svelte 4 was released today so would be great to support it, unfortunately it doesn't seem language tools does currently. Sent a draft PR to astro to work on supporting it in the code there https://github.com/withastro/astro/pull/7454. A list of breaking changes [can be found here](https://github.com/sveltejs/svelte/blob/master/packages/svelte/CHANGELOG.md#major-changes), but specifically I think we need to worry about:

> breaking: Minimum supported TypeScript version is now TypeScript 5 (it will likely work with lower versions, but we make no guarantees about that) (https://github.com/sveltejs/svelte/pull/8488)

> breaking: Deprecate SvelteComponentTyped in favor of SvelteComponent (https://github.com/sveltejs/svelte/pull/8512)

There may be more but I haven't looked at the implementation here. Happy to try and work on a pr at the end of this week if no one else wants to pick it up (may take some time to figure out as I am unfamiliar with the codebase).

### Proposed Solution

n/a

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by bluwy** [comment]
Can you explain how language-tools isn't working with Svelte 4? It's working fine for me.

**Comment by Princesseuh** [comment]
Yeah, since we updated to the latest version of `svelte2tsx` some time ago, it should already be working as far as I know.

**Comment by ghostdevv** [comment]
Nevermind it's working for me now :pray:
