### ISSUE TITLE
🐛 BUG: Extension's Astro file formatting overrides the Prettier plugin.

### ISSUE THREAD

**Issue by jiv-e** [withastro/language-tools#591]
### Describe the Bug

The problem is described here:
https://github.com/withastro/prettier-plugin-astro/issues/351

### Steps to Reproduce

1. Install the Astro extension in VS Code.
2. Install the prettier-plugin-astro for your project as instructed here: https://github.com/withastro/prettier-plugin-astro
3. Run 'Format Document' command on some .astro file.
4. Check that tabs are used for indentation instead of spaces that should be default for Prettier.
5. Check that running Prettier via command line formats the file correctly: 
`./node_modules/prettier/bin-prettier.js ./src/components/ --write --plugin=prettier-plugin-astro`

**Comment by Princesseuh** [comment]
This is most likely an upstream issue in Volar's Prettier service if anyone is interested in checking it out: https://github.com/volarjs/services/blob/master/packages/prettier/src/index.ts
