### ISSUE TITLE
🐛 BUG: VS Code quick-suggestions/autocompletion in .astro files is very slow

### ISSUE THREAD

**Issue by xriter** [withastro/language-tools#593]
### Describe the Bug

For some reason the autocompletion in vs code for `.astro` files is very slow.
It will just show 'Loading...' for a few seconds, before it comes up the suggestions.

When trying the same code in `.ts` files, the autocomplete suggestions come up instantly.

I tried disabling all other extensions, and resetting all settings to the defaults, but this made no difference.
I think the issue also worsens when the .astro files get bigger.

Am I the only one experiencing this?

### Steps to Reproduce

-

**Comment by johnsoncodehk** [comment]
Can you try if this version improves the problem?

[astro-vscode-2.0.19-alpha.1.vsix.zip](https://github.com/withastro/language-tools/files/11902443/astro-vscode-2.0.19-alpha.1.vsix.zip)

**Comment by Princesseuh** [comment]
Hello, does this still happen using the latest versions of the extension @xriter?

**Comment by Princesseuh** [comment]
Closing since it seems like this is fixed and there's no other reports of this. In general, the tips here can be useful to follow when having performance issues: https://github.com/microsoft/TypeScript/wiki/Performance
