### ISSUE TITLE
Add support for ignoring hints and warnings in `astro check`

### ISSUE THREAD

**Issue by arimgibson** [withastro/language-tools#604]
### What version of `astro` are you using?

2.5.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### What browser are you using?

N/A

### Describe the Bug

The `astro check` command is a diagnostics tool used to report errors detected inside .astro files. When using `<script>` tags inside an Astro files, these tags are bundled by default and offer TypeScript support. The TypeScript comment `// @ts-ignore` can be used in these bundled script tags to also silence errors thrown by `astro check`.

However, script tags that aren't bundled by using the `is:inline` directive don't acknowledge the ts-ignore comment and still throw errors. This makes sense as the files aren't TypeScript and don't know to recognize comments prefixed with `ts-`, but it makes it impossible to stop Astro from throwing on known and expected errors for JavaScript code.

The MRE linked should go to line 38 of `src/index.astro`, which has an inline script that isn't called anywhere in the code. When running `pnpm astro check` from the CLI, this error is reported despite having the `// @ts-ignore` comment one line above.

One solution could be to help the Astro language parser, which is used by the `check` command, to look for `ts-` comments even in inline scripts. If that's an acceptable fix, I could potentially submit a PR with some guidance; looking through some of that code right now.

Thanks!

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-d56kwk?file=src%2Fpages%2Findex.astro%3AL38&view=editor

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment]
Edited the title and moved to `language-tools` in order to better reflect the status (and needs) of the issue

**Comment by brunoprietog** [comment]
So is there any way to disable type suggestions in VS Code configuring some file in the project or something similar? I'm using custom elements inside `.astro` files using the `<script>` tag, and all the time I get annoying TypeScript errors. They disappear if I add types, but I don't want to add types, I want to write only JavaScript. I haven't found a way to disable it, it's getting very frustrating. Thanks for any help

**Comment by dbanswan** [comment]
> So is there any way to disable type suggestions in VS Code configuring some file in the project or something similar? I'm using custom elements inside `.astro` files using the `<script>` tag, and all the time I get annoying TypeScript errors. They disappear if I add types, but I don't want to add types, I want to write only JavaScript. I haven't found a way to disable it, it's getting very frustrating. Thanks for any help

Looking for same, writing in plain javascript and keep getting these under "Problems", wish there was a way to disable them.

**Comment by yungvldai** [comment]
To disable checking you can insert `// @ts-nocheck` comment after the opening `<script>` tag. For example:

```
---

<script>
    // @ts-nocheck        
    ...
</script>
```

This will completely disable checks in this file and it will not appear in the `astro check` report. Btw, astro will remove the comment when building.

**Comment by brunoprietog** [comment]
I know, but I want to disable this at the project level. If I'm writing in JavaScript, why do I have to write to every file that doesn't do type checking? Astro in the generator of a new application asks if I want to use TypeScript. I say no, then they shouldn't bother me with types anywhere.

**Comment by Princesseuh** [comment]
In a (hopefully soon) future version of the VS Code extension we'll have support for `typescript.validate.enable` to disable TypeScript validation. In the meantime, I don't think there's a workaround apart from using `// @ts-nocheck`.

I'll note that Astro is TypeScript-only, Astro files and hoisted script tags are always considered to be TypeScript. The prompt essentially tells you this when you say "No" to it, by saying that TypeScript is always supported.
