### ISSUE TITLE
💡 RFC: [VS Code] Let other icon themes override file icon

### ISSUE THREAD

**Issue by ng-hai** [withastro/language-tools#606]
### Background & Motivation

I encounter an issue that Rose Pine theme on VS Code cannot override Astro file icon, it makes my theme look inconsistent someway. I have opened an issue on their repo but it seems they can't fix the issue on their side.

rose-pine/vscode#88

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Hmm, as far as I know, we don't do anything to prevent the icon from being overriden, we define it the normal way

**Comment by Princesseuh** [comment]
Looked at the docs, and there's nothing we can do on our side. Icons themes are supposed to be able to override language icons specified by extensions. 

If it doesn't work, there might be an issue in VS Code itself, or perhaps the icon theme was misconfigured. There's a setting called "showLanguageModeIcons" that can be specified in the icon theme that could be relevant as well.

Sorry for the inconvenience
