### ISSUE TITLE
🐛 BUG: formatting .astro files throwing error in vscode

### ISSUE THREAD

**Issue by runeb** [withastro/language-tools#616]
### Describe the Bug

Invoking "Format Document" does nothing to the file and throws an error in the output for Astro Language Server

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/runeb/src/monorepo/node_modules/prettier-plugin-astro' is not supported resolving ES modules imported from /Users/runeb/src/monorepo/node_modules/prettier/index.mjs
Did you mean to import /Users/runeb/src/monorepo/node_modules/prettier-plugin-astro/dist/index.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:425:17)
    at moduleResolve (node:internal/modules/esm/resolve:1012:10)
    at defaultResolve (node:internal/modules/esm/resolve:1220:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ESMLoader.import (node:internal/modules/esm/loader:528:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/runeb/src/monorepo/node_modules/prettier-plugin-astro'
}
```

I have attempted to re-install the Astro extension and clear out node_modules reinstalling everything

### Steps to Reproduce

1. Initialize an Astro project as an app in a [turbo repo](https://turbo.build/repo) at `apps/web`
3. Use vim mode in vscode (no idea if its relevant)
4. Install the latest (v2.1.3) Astro vscode plugin and attempt to format an .astro file
5. See that nothing changes in the file and no error message displayed
6. Open the Output tab of vscode and see the error pasted above

**Comment by runeb** [comment]
Being careful to remove any local `prettier-plugin-astro` modules, the error is the same, but with different paths.

I also upgraded to `astro@2.9.3`

```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/runeb/.vscode/extensions/astro-build.astro-vscode-2.1.3-darwin-arm64/node_modules/prettier-plugin-astro' is not supported resolving ES modules imported from /Users/runeb/src/monorepo/node_modules/prettier/index.mjs
Did you mean to import /Users/runeb/.vscode/extensions/astro-build.astro-vscode-2.1.3-darwin-arm64/node_modules/prettier-plugin-astro/dist/index.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:425:17)
    at moduleResolve (node:internal/modules/esm/resolve:1012:10)
    at defaultResolve (node:internal/modules/esm/resolve:1220:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ESMLoader.import (node:internal/modules/esm/loader:528:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/runeb/.vscode/extensions/astro-build.astro-vscode-2.1.3-darwin-arm64/node_modules/prettier-plugin-astro'
}

}
```

**Comment by adamklepacz** [comment]
I'm facing exast same error on my side. :( The forrmatin doesn't work at all

**Comment by Loa212** [comment]
@adamklepacz 

Mee too. I tried both MacOs & Windows

**Comment by Loa212** [comment]
Sorry to bother by reopening the thread but I am still having trouble with this. 

- My Astro-extension-vscode version is v2.1.4
- MacOs

---
I tryed editing my Settings.json as per in structed in the astro-prettier-plugin (also tried removing that configuration with no luck)

error logged from prettier:

```
[...]
["INFO" - 15:15:56] PrettierInstance:
{
  "modulePath": "/Users/[...]/node_modules/prettier/index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 20,
  "version": "3.0.0"
}
[...]
["WARN" - 15:15:56] Parser not inferred, trying VS Code language.
["ERROR" - 15:15:56] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
```

**Comment by Princesseuh** [comment]
> Sorry to bother by reopening the thread but I am still having trouble with this. 
> 
> - My Astro-extension-vscode version is v2.1.4
> - MacOs
> 
> ---
> I tryed editing my Settings.json as explained in the [astro-prettier-plugin docs](https://github.com/withastro/prettier-plugin-astro#using-in-vs-code) (also tried removing that configuration with no luck)
> 
> error logged from prettier:
> 
> ```
> [...]
> ["INFO" - 15:15:56] PrettierInstance:
> {
>   "modulePath": "/Users/[...]/node_modules/prettier/index.cjs",
>   "importResolver": {},
>   "callMethodResolvers": {},
>   "currentCallMethodId": 20,
>   "version": "3.0.0"
> }
> [...]
> ["WARN" - 15:15:56] Parser not inferred, trying VS Code language.
> ["ERROR" - 15:15:56] Failed to resolve a parser, skipping file. If you registered a custom file extension, be sure to configure the parser.
> ```
> 
> 

This issue is about formatting with our extension, not Prettier's. Without seeing your config, I can't really help

**Comment by Loa212** [comment]
@Princesseuh 

What config would you need to see? should I create a separate issue? 

I am using the latest version of prettier (Prettier - Code formatter v9.19.0)
