### ISSUE TITLE
🐛 BUG: VSCode 'Format Document' does not respect editor indentation setting

### ISSUE THREAD

**Issue by FeldrinH** [withastro/language-tools#635]
### Describe the Bug

The 'Format Document' command in VSCode does not respect the editor indentation setting when formatting .astro files.

### Steps to Reproduce

1. `npm create astro@latest`
2. Open project in VSCode
3. Open any .astro file:
  ![image](https://github.com/withastro/language-tools/assets/5256211/e5799c30-7f29-4694-a47e-c2be87478a37)
5. Run 'Format Document'
7. Document is formatted using 2 spaces, even though the file was originally formatted using tabs and VSCode correctly detects this:
  ![image](https://github.com/withastro/language-tools/assets/5256211/639e7a40-c842-489a-9107-97fbcec98130)

**Comment by Princesseuh** [comment]
https://github.com/withastro/language-tools/pull/637 fixes this, however please note that Prettier's VS Code extension applies a default formatting config, even if none are configured, that will still overwrite the editor's config if it exists. We'll need further work to workaround that problem

However, if you're just using our extension, everything will work after that PR
