### ISSUE TITLE
@astrojs/check also analyzes hoisted scripts in dist

### ISSUE THREAD

**Issue by mandar1jn** [withastro/language-tools#643]
### Astro info

```block
Astro version            v3.0.1
Package manager          yarn
Platform                 win32
Architecture             x64
Adapter                  Couldn't determine.
Integrations             @astrojs/sitemap, @astrojs/tailwind
```

### What browser are you using?

Chrome

### Describe the Bug

@astrojs/check analyzes both the hoisted scripts in dist and normal files in the source folder

This results in a lot of console spam since astro check outputs the line where the warning occurs. For hoisted files, that's the whole file.

### What's the expected result?

Astro should not check the dist directory

### Link to Minimal Reproducible Example

Don't know how to write a minimum reproduction for this since I don't know what parts of my scripts result in warnings in the hoisted scripts. I know for sure this occurs on github.com/mandar1jn/portfolio

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by pringshia** [comment]
I'd suggest adding the following to the generated `.tsconfig.json` file, which also fixes the issue:

```
{
   "compilerOptions": {
      "outDir": "dist"
   }
}
```

Would this be a reasonable fix?

This issue was quite a pain point for me as a new user, in an otherwise very polished experience!

**Comment by MoritzLost** [comment]
+1 for this issue, just spent a couple minutes debugging this. Whatever the best solution, running `npm create astro@latest` should include it. You shouldn't get a bunch of errors after running `npm run build` a second time. Excluding the configured `outDir` should be the default.

**Comment by danielo515** [comment]
I came here from #11375, and the workaround indeed works, but this should be the default.
Thanks for considering it

**Comment by Princesseuh** [comment]
In Astro 5:
- All the examples includes `exclude: ['dist']` by default
- The presets all excludes `dist` by default (if using TS 5.5+)

For people on Astro 4, adding `exclude: ['dist']` to your `tsconfig.json` is the accepted workaround.
