### ISSUE TITLE
🐛 BUG: LSP couldn't locate the Astro in a monorepo

### ISSUE THREAD

**Issue by Stradi** [withastro/language-tools#644]
### Describe the Bug

Hi.

I am using Astro 3.0.5 in a monorepo-ish directory structure. Why monorepo-ish, because I'm not using any external tool to manage monorepo. I'm just creating folders for each app and package.

```
package.json -> Just a metadata information about the project itself.
apps/
  |- frontend/
      |- node_modules/
      |- package.json
      |- astro.config.mjs
      |- ...
  |- backend/
      |- node_modules/
      |- package.json
      |- ...
packages/
  |- some-helper-package
      |- node_modules/
      |- package.json
      |- ...
```

The problem is that the Astro page in `apps/frontend/src/pages/index.astro` has all the globals (`Astro` for example) recognized but `apps/frontend/src/pages/auth/sign-up.astro` page doesn't. After I move the Astro project (frontend directory) in `packages/` instead of `apps/` the error goes away.

VSCode shows a warning like this:

```Couldn't find Astro in workspace "/home/batin/projects/project-name". Experience might be degraded. For the best experience, please make sure Astro is installed into your project and restart the language server.```

The output panel for Astro Language Server is also showing an error:

```/home/batin/projects/project-name seems to be an Astro project, but we couldn't find Astro or Astro is not installed```

I've dig through the source code of Astro Language Server and found that language server only checks `packages/` directory for monorepos. I've also tested this by renaming `apps/` into `packages/` and it works. Here is the related code:

[packages/language-server/src/utils.ts#L27-L44](https://github.com/withastro/language-tools/blob/main/packages/language-server/src/utils.ts#L27-L44)

```ts
// If we couldn't find it inside the workspace's node_modules, it might means we're in the monorepo
try {
    astroPath = getPackagePath('./packages/astro', basePaths);

    if (!astroPath) {
        throw Error;
    }

    version = require(path.resolve(astroPath, 'package.json')).version;
} catch (e) {
    // If we still couldn't find it, it probably just doesn't exist
    console.error(
        `${basePaths[0]} seems to be an Astro project, but we couldn't find Astro or Astro is not installed`
    );

    return undefined;
}
```

I think LSP should check all directories except some big ones (like `node_modules`) and try to find Astro project that way.

### Steps to Reproduce

1. Create `apps/` directory in root folder
2. `cd` into `apps/` and run `pnpm create astro` with default options
3. Create a file in `apps/project-name/src/pages/test/test.astro`. The Astro global variable should not be recognized in this file.
4. Rename `apps/` into `packages/` and now the file in `packages/project-name/src/pages/test/test.astro` should be recognized by Astro LSP and has the `Astro` global variable.

**Comment by Princesseuh** [comment]
> I've dig through the source code of Astro Language Server and found that language server only checks packages/ directory for monorepos. I've also tested this by renaming apps/ into packages/ and it works. Here is the related code:

This code is about making it work inside **the** astro monorepo, as in the at https://github.com/withastro/astro, not monorepos in general. As you can see, it then look for `packages/astro`, which is where `astro` lives in that project.

I'm not sure how we could make this work for arbitrary folder structures, we really just do a `require.resolve` from the root of the workspace folder.

**Comment by cdtut** [comment]
> I'm not sure how we could make this work for arbitrary folder structures, we really just do a require.resolve from the root of the workspace folder.

@Princesseuh https://pnpm.io/pnpm-workspace_yaml `pnpm-workspace.yaml` is required in monorepo root and `packages` array in it can be used. That will let any package structure work for pnpm monorepo.

**Comment by pauliesnug** [comment]
I'm also experincing this issue. Even just a way to change the workspace root that Astro searches in would be awesome.

**Comment by lukaso** [comment]
I'm still having this problem.

What about a config such as:

```json
  "astro.language-server.workspaceFolders": [
    "./relative/path/to/astro/project"
  ]
```
