### ISSUE TITLE
🐛 BUG: Emojis mess with mapping inside inline script tags

### ISSUE THREAD

**Issue by vrifox** [withastro/language-tools#660]
### Describe the Bug

Everything in `onsubmit` gets “eaten” on every save when using Emojis!

### Steps to Reproduce

1. `npm init astro` using sample files, typescript strict on
2. In `src/components/Card.astro` replace `&rarr;` with an Emoji (example: 🌕)
3. Add `<form onsubmit="event.preventDefault()"></form>` after the a tag
4. Activate autoformat on save in VSCodium (Setting)
5. Error! Everything in `onsubmit` gets “eaten” on every save!

**Comment by Princesseuh** [comment]
This particular issue has been fixed by https://github.com/withastro/language-tools/pull/681, however there still seems to be some mapping problems when using multiple-bytes characters like emojis

**Comment by Princesseuh** [comment]
Closing in favour of https://github.com/withastro/language-tools/issues/862, since this issue was dedicated to another issue that has been fixed.
