### ISSUE TITLE
🐛 BUG: Other projects prompt astro refactoring

### ISSUE THREAD

**Issue by recallwei** [withastro/language-tools#666]
### Describe the Bug

When I work on other projects, even non-Astro projects, the Astro plugin will prompt for refactoring. Can I disable this behavior or prompt for refactoring only when the project contains astro dependencies?

### Steps to Reproduce

1. enable astro VSCode extension
2. open a React or Vue project
3. try to change the location of the component which imported into the page
4. the Astro extension prompt that should you refactor.

**Comment by recallwei** [comment]
First:
Astro Extension wants to refactor changes by moving this file
![image](https://github.com/withastro/language-tools/assets/62941121/d61ea0b7-6b69-4fc0-b7a2-858c034e3b03)
Then:
Whether to update the import of `footer.tsx`
![image](https://github.com/withastro/language-tools/assets/62941121/8edb7790-90bf-4cc1-be7f-eceaac8a2513)
Even though I'm not working on the Astro project.

**Comment by Princesseuh** [comment]
Hmm, this is most likely coming from our TypeScript plugin being always enabled, I'd assume. Not too sure if it's because of a misconfiguration, or if we should just disable the plugin when it's not an Astro project (which, in the past, when we used to do that, caused a lot of issues)

**Comment by Princesseuh** [comment]
This should be fixed now, the VS Code extension no longer handle imports renaming by default, leaving it to the TypeScript plugin.
