### ISSUE TITLE
🐛 BUG: [astro] Invalid file extension for Pages: .tsx

### ISSUE THREAD

**Issue by jangoergens** [withastro/language-tools#667]
### Describe the Bug

I created a project using Astro, Tailwind, Svelte, pnpm, and Typescript ([Link to project inside monorepo](https://github.com/jangoergens/frontend-portfolio/tree/main/apps/blog)).

Whenever I have the astro dev server running and I edit a .astro file, I get the warning `[astro] Invalid file extension for Pages: .tsx` with a `(xi)` behind it, where i is the number of edits I have done to the file. This appears without me saving anything. Sometimes an additional message appears, but not as a warning `[astro] update /src/pages/index.astro.tsx` despite me not having any `.tsx` files in that project.

When I disable the Astro extension, the warning disappears. I am unsure where to go from here, as I've not found this error message being discussed anywhere else.

### Steps to Reproduce

1. Create an astro project with Svelte and Typescript
2. Run pnpm start
3. Edit (e.g. add a new line) any .astro file in pages folder inside of VSCode with the Astro extension installed
4. Console warning: `[astro] Invalid file extension for Pages: .tsx`

**Comment by whoiscarlo** [comment]
Any update on this?

**Comment by Princesseuh** [comment]
Investigated the issue, and it's related to ESLint. I don't know what the issue is, but it's not related to us. I would suggest making an issue either on ESLint directly, or perhaps on the ESLint Astro plugin.
