### ISSUE TITLE
🐛 BUG: Generic vue types break depending how props are accessed in template.

### ISSUE THREAD

**Issue by minht11** [withastro/language-tools#684]
### Describe the Bug

Generic vue types break depending how props are accessed in template.
Lets take component like this, it all works fine: 
```vue
<script lang="ts">
export const customFormatter = (num: number) => `${num * 3}!!!`
export type FormatNumber<T> = (num: T) => string;
</script>

<script lang="ts" setup generic="T extends number, Formatter extends FormatNumber<T>">
const props = defineProps<{
	value: T,
	formatter: Formatter
}>()
</script>

<template>
	{{ value }} {{ props.formatter(props.value) }}
</template>
```
Now take the same component and instead user prop directy inside template without `props.` like this:
```vue
<script lang="ts">
export const customFormatter = (num: number) => `${num * 3}!!!`
export type FormatNumber<T> = (num: T) => string;
</script>

<script lang="ts" setup generic="T extends number, Formatter extends FormatNumber<T>">
defineProps<{
	value: T,
	formatter: Formatter
}>()
</script>

<template>
	{{ value }} {{ formatter(value) }}
</template>
```
And you will get `This expression is not callable. Type 'unknown' has no call signatures. `
<img width="614" alt="image" src="https://github.com/withastro/language-tools/assets/8914032/990443f2-2a29-4c4e-bd2a-fe6b72b05dfb">

### Steps to Reproduce

1. Copy paste second component example.
2. Observe `This expression is not callable. Type 'unknown' has no call signatures.` error.

**Comment by minht11** [comment]
Wrong repo. Sorry.

**Comment by Princesseuh** [comment]
Hello, the Astro tooling doesn't run in Vue files. You should make an issue over at https://github.com/vuejs/language-tools

(Though I'd imagine this syntax also causes issues for Astro)
