### ISSUE TITLE
🐛 BUG: Reload Window Required After Creating Layout or Component for Intellisense to Recognize

### ISSUE THREAD

**Issue by Daubenmire** [withastro/language-tools#685]
### Describe the Bug

Every time I create a new layout or component and attempt to use it I have to ctrl+shift+p -> Reload Window to refresh VSCode in order for Intellisense to recognize it and not give an error.
![image](https://github.com/withastro/language-tools/assets/145939919/b73a0ebb-5c6f-4054-ae7a-80f4bf44f1be)
![image](https://github.com/withastro/language-tools/assets/145939919/a4f47ebc-ab77-4d2d-9727-1e755a2d375f)

If I either close VS Code and reopen or I ctrl+shift+p -> Reload Window the component or layout will immediately be available and work correctly.
![image](https://github.com/withastro/language-tools/assets/145939919/d9537c13-b78c-44c8-99e0-59bc3bfcc05c)
![image](https://github.com/withastro/language-tools/assets/145939919/92605d20-8b8a-428f-9f1e-02a8ebee3e35)

### Steps to Reproduce

1. npm create astro@latest
2. open blank project
3. create a new layout (MainLayout.astro for ex.)
4. create a second layout (AnotherLayout.astro for ex.)
5. attempt to use <AnotherLayout/> in MainLayout.astro
6. sometime this second layout is recognized without issue.....
7. create a third layout (MainHead.astro for ex.)
8. attempt to use <MainHead/> in MainLayout.astro and it will not be recognized by intellisense and give an error. 
9. delete <MainHead/> tag
10. reload window
11. use <MainHead/> tag in MainLayout.astro and it will be recognized and work correctly.

**Comment by Daubenmire** [comment]
> If you try to use the quick fix to import the component, does it work?

Yes the quick fix will bring up a window to allow you to import it. 

![image](https://github.com/withastro/language-tools/assets/145939919/cbab0308-02be-4811-ae7a-ac610f585537)

I also just noticed while trying to test this that it looks like the first one I create will work and import correctly after opening a new project but successive ones will not.

I opened VSCode, created layout QuickFix.astro and went to put it in MainLayout.astro and intellisense worked correctly. Making the second layout called AnotherQuick.astro and trying to insert in Mainlayout.astro gave the same bug as reported. I was able to test the quick fix on <AnotherQuick /> and get it to import. Screenshot is from a third layout showing quick fix pop-up.

**Comment by Princesseuh** [comment]
I believe this is a bug in https://github.com/volarjs/typescript-auto-import-cache, thank you for the issue!

**Comment by sammwashere** [comment]
Is there a way to maybe disable the typescript auto import cache in VS Code?

**Comment by Brian-ChM** [comment]
I have the same problem, it seems to happen only on linux.

**Comment by nasheomirro** [comment]
Happens on Windows as well. I also want to add that Astro files still show as suggestions even when they are deleted until the next reload/restart of the extension, it doesn't add the import statements if you do click or press enter on the bugged suggestion.

**Comment by einarmagnus** [comment]
For what it is worth: it is enough for me to run "Astro: reload project" to get it working again. That's a lot quicker than reloading the whole window.

**Comment by Princesseuh** [comment]
The latest version of the extension should improve the problem here somewhat, however there are still some issues remaining. Apologies for the inconvenience, it was a tough nut to crack!

**Comment by Reimirno** [comment]
Same problem on windows. (astro extension v2.8.4)
