### ISSUE TITLE
VSCode: JSX {} dynamic operator isn't higlighted

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#7]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

The JSX {} dynamic operator isn't higlighted

### Steps to Reproduce

The JSX {} dynamic operator should be higlighted

**Comment by matthewp** [comment]
@RafidMuhymin can you provide an example of how this is highlighted in JSX but is not being highlighted in Astro? In my theme there is no special color provided to either of these. If there's a theme you use where that's not the case please let me know so I can check it out.

**Comment by RafidMuhymin** [comment]
@matthewp Astro:
![image](https://user-images.githubusercontent.com/63650415/144274551-20b4c64c-a456-4d42-a198-bc3afb42e84c.png)

JSX:
![image](https://user-images.githubusercontent.com/63650415/144274828-be9d8577-2eaf-44e1-9bd0-010965b5ed13.png)

**Comment by RafidMuhymin** [comment]
Minimal repro:
```astro
---
// Please view the code in VSCode. Highlighting in GitHub is different from VSCode
---

<!DOCTYPE html>
<html>
  <body>
    <!-- The JSX {} operator isn't highlighted property in the following lines -->
    <h1>Hello {src}!</h1>
    <img {src} />

    <!-- The inner JSX {} operator in the following line is highlighted properly -->
    {(<img src={src} />)}
  </body>
</html>
```

**Comment by Princesseuh** [comment]
This was fixed, however something to note is that you very rarely see native highlighting for brackets these days due to VS Code's bracket colorization. So to see the updated colors, you'd have to disable that
