### ISSUE TITLE
Typescript warning when using `define:vars` on script tag

### ISSUE THREAD

**Issue by jsve** [withastro/language-tools#711]
### Astro Info

```block
Astro                    v3.3.2
Node                     v18.18.2
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @gamesome/astro-font
```

### Describe the Bug

When using a tag like this:
```javascript
<script is:inline define:vars={{ first_var, second_var }}>
```

The `first_var` and `second_var` are not recognised as defined. I get a warning in vscode and in the terminal when building: `ts(2570) - Could not find name...`

Using `ts-ignore` does not work for the individual lines. `ts-nocheck` right after the script tag works, but that's not ideal.

### What's the expected result?

Ideally typescript should recognise these variables, at least during the build.

If `@ts-nocheck` is the intended solution, this should be reflected in the documentation (https://docs.astro.build/en/reference/directives-reference/#definevars)

### Link to Minimal Reproducible Example

https://docs.astro.build/en/reference/directives-reference/#definevars

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by lilnasy** [comment]
@Stark-X I see the first serverURL example results in an error, and that can be fixed. Although, the second gTag example is only a hint. It is not ideal because it is being noisy, but it might be trickier to ignore.
<img width="576" alt="image" src="https://github.com/withastro/language-tools/assets/69170106/15955ef7-15b8-4aaf-b83f-492c1dab5d27">

**Comment by jorgejhms** [comment]
I'm getting this error again with Astro 4.11.5. It's preventing me to build a website.

```
> astro check && astro build

15:40:26 [types] Added src/env.d.ts type declarations.
15:40:26 [types] Added src/env.d.ts type declarations.
15:40:26 Types generated 201ms
15:40:26 [check] Getting diagnostics for Astro files in /Users/jorgejhms/code/salvapied...
src/components/Semaforo.astro:96:16 - error ts(2339): Property 'src' does not exist on type 'HTMLElement'.

96       semaforo.src = isDarkMode ? optimizedGreenWhite.src : optimizedGreen.src;
                  ~~~
src/components/Semaforo.astro:93:18 - error ts(2339): Property 'src' does not exist on type 'HTMLElement'.

93         semaforo.src = isDarkMode ? optimizedRedWhite.src : optimizedRed.src;
                    ~~~
src/components/Semaforo.astro:89:16 - error ts(2339): Property 'src' does not exist on type 'HTMLElement'.

89       semaforo.src = isDarkMode
                  ~~~
src/components/Semaforo.astro:79:32 - error ts(7006): Parameter 'element' implicitly has an 'any' type.

79     const getBottomPosition = (element) =>
                                  ~~~~~~~

src/components/TopBar.astro:9:9 - warning ts(6133): 'prevScrollpos' is declared but its value is never read.

9     let prevScrollpos = window.scrollY;
          ~~~~~~~~~~~~~

src/pages/semaforo/[slug].astro:47:16 - error ts(2339): Property 'src' does not exist on type 'HTMLElement'.

47       semaforo.src = optimizedSemaforo.src;
                  ~~~
src/pages/semaforo/[slug].astro:45:16 - error ts(2339): Property 'src' does not exist on type 'HTMLElement'.

45       semaforo.src = optimizedSemaforoWhite.src;
                  ~~~

Result (39 files):
- 6 errors
- 0 warnings
- 1 hint
```

**Comment by Princesseuh** [comment]
Those errors looks normal to me. If you don't want type checking to prevent you from building, remove `astro check` from your build script.

**Comment by jorgejhms** [comment]
There should not be type errors here, as I'm using define:bars so the script code is written on JavaScript (not typescript).

**Comment by Princesseuh** [comment]
If you're using a preset where `checkJs` is enabled, JavaScript files are checked as well. Things seems to be working on my end regarding it being JavaScript when using define:vars. Please share a reproduction if you think there's a bug.
