### ISSUE TITLE
🐛 BUG: Auto add missing imports dont work well

### ISSUE THREAD

**Issue by TheElegantCoding** [withastro/language-tools#715]
### Describe the Bug

in my vscode config i have this line of code, this let me save the file and let vscode auto import the missings imports, but this dont work well

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.addMissingImports": true
  },
}
```

as you can see in the photo, this add the import in the top of the line not where it should go

![image](https://github.com/withastro/language-tools/assets/70770072/16364189-c1cc-4402-b23e-5b2df66d891a)

### Steps to Reproduce

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.addMissingImports": true
  },
}
```

**Comment by Princesseuh** [comment]
Thank you for this issue! Mapping imports is always a bit tricky, ha.
