### ISSUE TITLE
🐛 BUG: ASCII is not syntax highlighted

### ISSUE THREAD

**Issue by kyleshevlin** [withastro/language-tools#719]
### Describe the Bug

In HTML, JSX, and TSX files, ASCII such as `&nbsp;` will get syntax highlighted to differentiate it from the text around it. Astro files do not yet.

![Screen Shot 2023-12-10 at 11 56 24 AM](https://github.com/withastro/language-tools/assets/4333144/f458e971-9f26-4cb5-ac79-d088c91bf61a)

With my theme, I would expect those `&nbsp;`s to be purple.

### Steps to Reproduce

1. In VSCode (I don't know if it happens in other editors), open an Astro file
2. Add an ASCII character, such as `&nbsp;` (non-breaking space character)
3. Note it is not highlighted

**Comment by Princesseuh** [comment]
Fixed by https://github.com/withastro/language-tools/pull/824
