### ISSUE TITLE
🐛 BUG: astro check reports incorrect errors on HTMLAttributes

### ISSUE THREAD

**Issue by DerYeger** [withastro/language-tools#727]
### Describe the Bug

While this worked as expected in Astro 4.0.4, `astro check` now reports entirely valid JSX attributes as invalid HTMLAttributes.
I've created a tiny reproduction here: https://stackblitz.com/edit/github-ckecs3?file=package.json.
Running `npm run check` will show that both `onClick` and `className` are invalid, even though both are in fact valid JSX props.

### Steps to Reproduce

1. Run `npm create astro@latest -- --template framework-preact`
2. Add `"check": "astro check:"` to the `scripts` section
3. Run `npm run check`
4. The valid `onClick` attributes are considered errors. Now, changing one of the `class` attributes to `className` (which is valid) will also show that as an error.

**Comment by Princesseuh** [comment]
Hmm, seems like it's not taking into account the `tsconfig.json` correctly, for some reason. To be clear, this also didn't work in the past, it's just that I recently fixed a bug where it ignored errors completely inside certain files.

**Comment by millette** [comment]
I'm seeing the same error with my solidjs components.

**Comment by Princesseuh** [comment]
I'll take a look once I'm back to work next week (if someone doesn't before me). Apologies for the inconvenience. In the meantime, pinning `@astrojs/check` to `0.3.2` would at least make it not fail (but would go back to the behavior where it didn't check certain files)

**Comment by flmn** [comment]
I have the same problem with React component.

**Comment by jlarmstrongiv** [comment]
Unfortunately, downgrading to `0.3.2` didn’t fix it for me

**Comment by Princesseuh** [comment]
> Unfortunately, downgrading to `0.3.2` didn’t fix it for me

You might need to override the language-server version manually, unfortunately. Hoping to have a fix out today, sorry for the delay.

**Comment by craigjennings11** [comment]
@jlarmstrongiv I had to revert my `pnpm-lock.yaml` file as well as downgrade to get it working again. Downgrading alone left some other dependency upgraded that made it keep failing.

**Comment by Princesseuh** [comment]
Okay, this is proving to be much harder than anticipated due to bugs in TypeScript itself. It'll take more time to figure out, so in the meantime I'll revert the `astro check` fix to what it did before (where it skipped over .js(x) files). 

Sorry for the inconvenience, TypeScript really wasn't made to have multiple JSX typings in the same project.

**Comment by knpwrs** [comment]
> TypeScript really wasn't made to have multiple JSX typings in the same project.

Indeed, though this worked for me in the past (prior to noticing this issue just the other day):

`tsconfig.json`:

```json
{
  "extends": "astro/tsconfigs/strict",
  "compilerOptions": {
    "rootDirs": [
      "./src/components/preact",
      "./src/components/react",
      "./src/components/solid"
    ]
  }
}
```

`src/components/preact/tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "jsx": "react-jsx",
    "jsxImportSource": "preact"
  }
}
```

`src/components/react/tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "jsx": "react-jsx"
  }
}
```

`src/components/solid/tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

`astro.config.mjs`:

```js
import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import preact from "@astrojs/preact";
import solid from "@astrojs/solid-js";

// https://astro.build/config
export default defineConfig({
  integrations: [
    preact({ include: ["**/preact/**"] }),
    react({ include: ["**/react/**"] }),
    solid({ include: ["**/solid/**"] }),
  ],
});
```

**Comment by Princesseuh** [comment]
Just released a hotfix (`0.3.4`) that disable checking JSX and TSX files in the meantime. Sorry again for the inconvenience, I'm still working on it and will hopefully find a solution 🫡

**Comment by oanaOM** [comment]
If any help, I'm facing the same issue. When running `astro check`, I get the following errors:

<img width="1232" alt="image" src="https://github.com/withastro/language-tools/assets/15228388/1469e385-83e6-4071-b84b-1b1db809a4a9">

**Comment by Princesseuh** [comment]
Make sure to update to the latest version of `@astrojs/check` for a temporary workaround!

**Comment by saidhasyim** [comment]
Hello, I'm using the latest `"@astrojs/check": "^0.7.0"` but the error still happens to me. Any other place I should update?

![image](https://github.com/withastro/language-tools/assets/111839161/f85cfbc7-2edd-4e24-b57f-0b931ea42ac2)

**Comment by Princesseuh** [comment]
> Hello, I'm using the latest `"@astrojs/check": "^0.7.0"` but the error still happens to me. Any other place I should update?
> 
> ![image](https://github.com/withastro/language-tools/assets/111839161/f85cfbc7-2edd-4e24-b57f-0b931ea42ac2)
> 

That's not the same issue, in what kind of file is that screenshot from?

**Comment by saidhasyim** [comment]
> > Hello, I'm using the latest `"@astrojs/check": "^0.7.0"` but the error still happens to me. Any other place I should update?
> > ![image](https://private-user-images.githubusercontent.com/111839161/331424349-f85cfbc7-2edd-4e24-b57f-0b931ea42ac2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTM1ODEsIm5iZiI6MTcxNTkxMzI4MSwicGF0aCI6Ii8xMTE4MzkxNjEvMzMxNDI0MzQ5LWY4NWNmYmM3LTJlZGQtNGUyNC1iNTdmLTBiOTMxZWE0MmFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwMjM0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2VlYjM3YmIwYmE3MzBjOWE0MjExMjY1OTA5ZDkwYmUyOWQ5Zjc5YzU5OTIyZjIyNzU2ZjQ1NjZkN2FkNGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JBL-6TgwGnNA-tQHzo2eKbo0tpVHuZnHN2B94O9Yfxc)
> 
> That's not the same issue, in what kind of file is that screenshot from?

Oh, I apologize. It is in `.astro` file. Would you know what I can do with this?

**Comment by Princesseuh** [comment]
Ah yes, Astro uses standard HTML attributes, so you should use `class`

**Comment by saidhasyim** [comment]
I see. That works! Thanks so much.

**Comment by metters** [comment]
`astro check` worked before I installed @astrojs/react, but now it does not anymore.

The expected value of `satori` changes from `VNode` to `ReactNode`:
<img width="500" alt="Screenshot 2024-06-25 at 21 41 41" src="https://github.com/withastro/language-tools/assets/9088722/b1ed3224-e2b6-4889-9f98-21586f27075e">

The [run of the GitHub Action](https://github.com/metters/astro-theme-cactus/actions/runs/9668291032) failed on the [updated branch](https://github.com/metters/astro-theme-cactus/pull/2).

Before that it still worked.

What I am asking is:
* Is this issue ([#727](https://github.com/withastro/language-tools/issues/727)) the same I am experiencing?
* Is this a satori bug or an astro bug?

Thank you very much in advance!
