### ISSUE TITLE
🐛 BUG: Updates in typescript types are only recognized after restarting the LSP

### ISSUE THREAD

**Issue by t-ober** [withastro/language-tools#742]
### Describe the Bug

I am using the astro language server with lspconfig in neovim.

Whenever I am updating a typescript type, e.g. renaming a variable, this change does not get picked up by the language server within astro files. The change is only recognized when I restart the LSP. 

There seems to be this similar issue: #489
It does not seem to be actually resolved. 

I can see that a `didChangeWatchedFiles` is being sent: 

```
[DEBUG][2023-12-27 09:58:21] .../vim/lsp/rpc.lua:284	"rpc.send"	{  jsonrpc = "2.0",  method = "workspace/didChangeWatchedFiles",  params = {    changes = { {        type = 1,        uri = "file:///Users/thomas/coding/js/immo-patt/src/interfaces/interface.ts"      } }  }
```

But it does not seem to be picked up by the language server. 

Does anybody have anyidea

### Steps to Reproduce

1. Set up neovim with lspconfig and the astro language server
1. Import a typescript type in an astro file
2. Change a type definition in a typescript file
3. Notice that the change does not get reflected within the astro file until the language server is restarted

**Comment by Princesseuh** [comment]
Since this works for VS Code, https://github.com/yaegassy/coc-astro and there's many people using the language-server in Neovim, I can only assume that this is a configuration issue in Neovim, but I honestly don't know. Thank you for reporting the issue, we'll take a look as soon as possible.

**Comment by Odas0R** [comment]
I've tried this right now and it's working on my end.

https://github.com/withastro/language-tools/issues/489#issuecomment-1870501815

**Comment by t-ober** [comment]
Thanks both of you for your feedback!
This then seems to be a layer 8 problem. Since I am new to the whole nvim thing I admittedly barely know what I am doing.  

@Odas0R : Would you mind sharing your lspconfig setup with me ? I still can't quite get it to work.

**Comment by Odas0R** [comment]
> Thanks both of you for your feedback! This then seems to be a layer 8 problem. Since I am new to the whole nvim thing I admittedly barely know what I am doing.
> 
> I made sure to update and reinstall the astro-language-server also the problem does not come up when importing type definitions in `.ts` files.
> 
> @Odas0R : Would you mind sharing your lspconfig setup with me ? I still can't quite get it to work.

Here: https://github.com/Odas0R/dot/blob/main/nvim/lua/odas0r/plugin/lsp.lua

Hope it helps! It's pretty basic

**Comment by Princesseuh** [comment]
Closing since this seems to be a setup issue. Many people are using Astro in Neovim just fine.

**Comment by emonadeo** [comment]
I have the same issue and I have been stuck on it for days and it's driving me nuts. What is the gotcha here that I am missing? I can't get it to work on either Neovim 0.9 or 0.10-dev.

- @astrojs/language-server v2.6.2
- astro v4.3.2
- typescript v5.3.3
- typescript-language-server v4.3.2

Even if I get rid of my entire config and only include nvim-lspconfig, file changes don't get recognized until I do `:LspRestart`:

(Using lazy.nvim)
```lua
{
	"neovim/nvim-lspconfig",
	config = function()
		require('lspconfig').astro.setup({
			capabilities = {
				workspace = {
					didChangeWatchedFiles = {
						dynamicRegistration = true,
					},
				},
			},
		})
		require('lspconfig').tsserver.setup({
			capabilities = {
				workspace = {
					didChangeWatchedFiles = {
						dynamicRegistration = true,
					},
				},
			},
		})
	end
},
```

**Comment by emonadeo** [comment]
With @astrojs/language-server 2.7 upgrading internally to Volar 2 fixed it! 🎉
