### ISSUE TITLE
🐛 BUG: latest version of Astro extension in vscode showing errors

### ISSUE THREAD

**Issue by Seokhyeon315** [withastro/language-tools#754]
### Describe the Bug

![image](https://github.com/eclipse/openvsx/assets/72924651/65cab0f7-5f7c-433d-b3f1-7f956a41a1fe)
After I updated the astro extension in vscode to 2.6.1, I am getting the error on HTML side of code. 
It recommends to change to className like jsx/tsx but if I change them the code will not working with Tailwindcss. 

It just showing the red underline error on the vs code but the whole code works fine. 
It's just annoying the red underlines when there is nothing wrong. I hope this will be fixed soon! 

### Steps to Reproduce

1. Updated Astro extension in vscode to 2.6.1.

**Comment by Princesseuh** [comment]
The latest version is 2.6.2, please update.
