### ISSUE TITLE
🐛 BUG: [ERROR] The build was canceled

### ISSUE THREAD

**Issue by millette** [withastro/language-tools#757]
### Describe the Bug

With astro 4.2.1 and @astro/check 0.4.1, running ```astro check``` displays **[ERROR] The build was canceled** yet the check goes on:

```
✘ [ERROR] The build was canceled

17:59:16 Types generated 77ms
17:59:16 [check] Getting diagnostics for Astro files in /home/millette/travail/robin/robin.millette.info...
Result (9 files):
- 0 errors
- 0 warnings
- 0 hints
```

### Steps to Reproduce

1. `npm init`
2. `npm i astro`
3. `npm i @astrojs/check`
4. `node_modules/.bin/astro check`
5. Error! (*see above*)

**Comment by millette** [comment]
Not sure why but the error vanished and I wasn't able to reproduce it in my other projects or in a minimal project.

**Comment by Princesseuh** [comment]
Either way, this error comes from `esbuild` which `astro check` doesn't run, ha! Glad you got it fixed, though.
