### ISSUE TITLE
🐛 BUG: Autocompletion for imports not working for new subdirectories (like "components/ui")

### ISSUE THREAD

**Issue by sammwashere** [withastro/language-tools#760]
### Describe the Bug

When I create a new subdirectory in components directory (or in layouts directory, both dont work), I can't get autocompletion for the component (both in the HTML and in the import statement).

### Steps to Reproduce

1. bun create astro@latest
2. use strict typescript
3. create "newdir" directory inside "components" directory
4. create a new component inside this directory (like "ComponentName.astro")
5. Error: I get no autocompletion for this new component in already existing components

**Comment by Princesseuh** [comment]
Duplicate of https://github.com/withastro/language-tools/issues/685
