### ISSUE TITLE
🐛 BUG: Regression in @astrojs/ts-plugin 1.5.0

### ISSUE THREAD

**Issue by castarco** [withastro/language-tools#775]
### Describe the Bug

Once I upgrade from @astrojs/ts-plugin 1.4.0 to 1.5.0, the `astro build` step starts to complain about encountering TS code inside some `<script>` blocks that I have in `.astro` files.

This didn't happen before.

### Steps to Reproduce

1. Start using `@astrojs/ts-plugin 1.4.0`
2. Create some `.astro` file with `<script>` block in it
3. Add some TS code in the `<script>` block
4. Everything should compile well
5. Update to 1.5.0
6. Try to build, and see how now Astro complains

**Comment by andrewbarnesweb** [comment]
Thought I was losing my mind this afternoon! Tried installing a clean project and all sorts to see if it would recognise the TS stuff.

**Comment by Princesseuh** [comment]
Ah yes, I can confirm the issue, apologies for the inconvenience. I'll take a look right now!

**Comment by Princesseuh** [comment]
Should be fixed in the latest version of everything, sorry for the inconvenience!

**Comment by andrewbarnesweb** [comment]
Can confirm working in 2.7.1! Thanks for sorting so quickly.
