### ISSUE TITLE
Multi-line semantic highlighting breaks

### ISSUE THREAD

**Issue by AmadeusTwi** [withastro/language-tools#780]
Type: <b>Bug</b>

Try using this code as an example:
```
  const [approveSelection, { error: approveError }] = useMutation<
    {
      acceptedOn: string;
    },
    {
      approveInput: IGraphqlApproveSelfSelectedRecommendationInput;
    }
  >(APPROVE_RECOMMENDATION_MUTATION);
```

Screenshots for visual representation of the bug:
<img width="442" alt="Broken formatting" src="https://github.com/withastro/language-tools/assets/23616925/bb662bdd-2a86-44f5-979a-889d7d203b51">
<img width="447" alt="Proper formatting" src="https://github.com/withastro/language-tools/assets/23616925/dcc1bf6c-d801-4104-8a49-8b5ab0b4aaa5">

Because generics of TS are written in multiple lines, useMutation loses it's semantic colors and becomes a plain-text colored.

Extension version: 2.7.1
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 9a8bd985-a46a-4c87-8a0d-04e08a57d25b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
d6fi2104:30959263
pydisww2:30959801
b1063948:30958189
3ef8e399:30949928
bg6jg535:30958357

```

</details>

**Comment by Princesseuh** [comment]
Just to be clear, this is inside an Astro file, right?

**Comment by ArmandPhilippot** [comment]
Even if this is an `.astro` file, VSCode will use the TextMate grammar files for TypeScript to highlight the code. You can see that by using the tokens inspector (`ctrl+maj+p` > `Developer: Inspect Editor Tokens and Scopes`):

![astro-typescript](https://github.com/withastro/language-tools/assets/59021693/8cf8a3a6-7903-4597-a4fb-adfc7bedfd8c)

So I don't think it is an Astro issue. The syntax highlighting is often broken with multi-line generics. It seems to be a known limitation of  TM Language syntax, see: https://github.com/microsoft/TypeScript-TmLanguage/issues/475

**Comment by Princesseuh** [comment]
This issue seems to be about semantic highlighting, not syntax highlighting. The former is powered by the Astro language server, as such it could very well be specific to us.

**Comment by AmadeusTwi** [comment]
> Just to be clear, this is inside an Astro file, right?

Nope, it is `.tsx` file.

**Comment by Princesseuh** [comment]
The latest version of the extension fixed some semantic highlighting related issues, does the issue still happen?

**Comment by AmadeusTwi** [comment]
No, it doesn't. Seems to be fixed! Thank you ^^.
