### ISSUE TITLE
🐛 BUG: class and object constructors lose their color on VS Code Astro extension

### ISSUE THREAD

**Issue by Firgrep** [withastro/language-tools#788]
### Describe the Bug

The astro extension on VS code appears to switch off the green coloring for class objects. `Object` and `NextResponse` should be green, but instead they're light-blue like normal variables. (I'm using color theme dark modern, but it appears to also affect other themes).

![Screenshot 2024-02-12 133304](https://github.com/withastro/language-tools/assets/118931755/f1bf12b8-685a-49eb-881d-dd6ce9271c80)
![Screenshot 2024-02-12 133311](https://github.com/withastro/language-tools/assets/118931755/02fbdfbc-70e3-4161-9474-bfdcccb958c6)

### Steps to Reproduce

1. Have Astro extension installed on VS Code.
2. Open up or make a typescript file and make a class constructed object, e.g. `Object.keys(someObject)` and see that `Object` is not appearing as normally green in VS Code's color config.
3. Go to extensions and disable Astro.
4. Watch the color of `Object` revert to green as expected.

**Comment by Princesseuh** [comment]
Great catch! It seems like this works inside Astro files directly, so it must be something related to our TypeScript plugin.
