### ISSUE TITLE
🐛 BUG: Auto import uses wrong line number within `script` for class decorators

### ISSUE THREAD

**Issue by bholmesdev** [withastro/language-tools#805]
### Describe the Bug

Language tools insert auto-import suggestions on the wrong line while using experimental decorators. This does not occur in TS files, only Astro `script` tags. Also confirmed the presence of `@controller` in the example does not matter.

https://github.com/withastro/language-tools/assets/51384119/9f2dfd5b-06d4-4724-8e7c-a3f399f23b9f

### Steps to Reproduce

1. Configure Astro project to use experimental decorators:

```json
{
  "extends": "astro/tsconfigs/strictest",
  "compilerOptions": {
    "target": "ES2020",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
  }
}
```

2. Install a third party dependency that exposes decorators, like `@github/catalyst`
3. Set up a class in a `script` tag
4. Attempt to auto-import a decorator like `@attr` within the class

**Comment by Princesseuh** [comment]
Strange, I feel like we don't touch the mappings at all inside script tags (or at least, we're not supposed to). I'll investigate, thank you for reporting this issue!
