### ISSUE TITLE
🐛 BUG: Language server fails to launch on latest VSCodium version (1.86.x, flatpak)

### ISSUE THREAD

**Issue by Mitsunee** [withastro/language-tools#806]
### Describe the Bug

The language server tries to access a directory that does no longer exist in VSCodium 1.86.x (flathub)

![Screenshot_20240223_133358](https://github.com/withastro/language-tools/assets/19474909/f28bdef9-383d-4b1f-b83a-5cb13a3538cd)

I have tried downgrading VSCodium until I found a version that works again and the directory does seem to exist in version 1.85.2:

![Screenshot_20240223_135215](https://github.com/withastro/language-tools/assets/19474909/c75d2441-210b-4d77-9a75-4715eff61c12)

Last known good version of VSCodium:

```
Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:30:44.948Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.7.4-200.fc39.x86_64
```

### Steps to Reproduce

1. Install VSCodium 1.86.x
2. Install Astro Extension
  - potentially need to relaunch codium
3. Language server fails to launch

### Further Notes

- Flatpak installation of VSCodium can be found at the location `/var/lib/flatpak/app/com.vscodium.codium/current/active/files/share/codium/` which is equal to `/app/share/codium` within the flatpak filesystem sandbox.
- I am unsure how to update extension manually, I am currently running version `v2.7.5` of the extension
- I presume the extension may want to pull from the Workspace's node_modules instead of the IDE installation to match version with the runtime of the Astro dev server? This may point to this being a different bug and the way I found it to just be a coincidence

### Temporary Workarounds

Rolling back to 1.85.2 does the trick just fine, here's how to do it with flatpak:

```shell
sudo flatpak update --commit=52dc04f145cc81fb71351068ebe07d535090d89fbffc4a1dc04b6ac683f4e362 com.vscodium.codium
sudo flatpak mask com.vscodium.codium # this locks the version
# to remove lock after this issue gets resolved:
sudo flatpak mask --remove com.vscodium.codium
```

Commands do need sudo unless when using `--user` for a user-installation of the codium flatpak

**Comment by Princesseuh** [comment]
> I presume the extension may want to pull from the Workspace's node_modules instead of the IDE installation to match version with the runtime of the Astro dev server? This may point to this being a different bug and the way I found it to just be a coincidence

We support both, you can change the TypeScript version being used using the command palette (much like you can for TypeScript itself). Supporting both is the best thing to do because the workspace might not have a TypeScript version (ex: an untitled workspace)

I'll look into the issue, wonder where they moved it, ha.

**Comment by lesar** [comment]
Same problem using fedora 39 codium installed by 
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/
using the repository standard: `dnf install codium`

> [Error - 17:21:18] Astro Language Server client: couldn't create connection to server.
  Message: Request initialize failed with message: Can't find typescript.js or tsserverlibrary.js in /usr/share/codium/resources/app/extensions/node_modules/typescript/lib
  Code: -32603 

I try using lunarvim too but get this [error](https://github.com/LunarVim/LunarVim/issues/4508)

best regards,
Leonardo

**Comment by Princesseuh** [comment]
Seems like it's a bug on VS Codium side https://github.com/VSCodium/vscodium/issues/1809 that has been fixed

**Comment by Mitsunee** [comment]
Just checked and it seems the vscodium update with the fix for this issue is available on flathub now. Launched into a project with astro, no errors, the `node_modules` directory seems to be back where it belongs. Thanks for looking into it 👍🏻
