### ISSUE TITLE
🐛 BUG: Emmet doesn't work inside a component

### ISSUE THREAD

**Issue by RafidMuhymin** [withastro/language-tools#81]
### Describe the Bug

Emmet doesn't work inside a component

### Steps to Reproduce

Emmet should work inside components

**Comment by SeizeDub** [comment]
Same issue here

**Comment by Princesseuh** [comment]
I'm not sure what you mean by inside a component? For me Emmet works in both components files and inside slots

**Comment by RafidMuhymin** [comment]
@Princesseuh The below GIF may help you understand the issue better

![Peek 2022-03-04 15-44](https://user-images.githubusercontent.com/63650415/156739877-a990ff71-1583-491e-84ae-15ce8a9fa45f.gif)

**Comment by Princesseuh** [comment]
@RafidMuhymin  Hmm, for me it works in slots, I'll investigate what's happening, thank you!
