### ISSUE TITLE
💡 RFC: the language tools shouldn't offer JS/TS completions in HTML code

### ISSUE THREAD

**Issue by PierBover** [withastro/language-tools#816]
### Background & Motivation

When writing HTML I'm getting all sorts of weird suggestions. Such as:

<img width="850" alt="image" src="https://github.com/withastro/language-tools/assets/226483/7f4beed0-3e0a-4f2b-9ffd-2da590ce15aa">

Not sure if this is a bug or a feature... but these JS/TS suggestions should not be happening when writing HTML.

### Possible solutions
JS/TS suggestions should only occur in JS contexts such as the front matter or dynamic expressions inside `{}`.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by Princesseuh** [comment]
Could you share the file in which this happens?

**Comment by PierBover** [comment]
I guess it's ok since it's a public blog post.

https://gist.github.com/PierBover/ad23cc9f1134b06a56d13ff1d0aad933

**Comment by Princesseuh** [comment]
Awesome, thank you! I'll take a look as soon as possible. It might be tough to fix because of how this works internally, but I'll see what I can do.

**Comment by r-o-l-a-n-d** [comment]
but you're writing in an .astro file? not an .html file. Isn't that just the regular IntelliSense feature to insert astro components (which get automatically linked in the frontmatter, in case you haven't used that component before)?

**Comment by PierBover** [comment]
But that intellisense should only trigger after typing `<`, no?

It's now triggering in actual text.

**Comment by r-o-l-a-n-d** [comment]
> But that intellisense should only trigger after typing `<`, no?
> 
> It's now triggering in actual text.

doesn't this depend on your VS Code settings? I think by default if you type "p" or "div" without "<" it also autosuggests creating a p or div element. Hierachy wise that's not really different to entering a  predefined <component />, so i would also expect "component" to show up as an autosuggestion if i start typing "com".

**Comment by PierBover** [comment]
> doesn't this depend on your VS Code settings? I think by default if you type "p" or "div" without "<" it also autosuggests creating a `<p>` or `<div>` element. Hierachy wise that's not really different to entering a predefined `<component />`, so i would also expect "component" to show up as an autosuggestion if i start typing "com".
> 
> [VSC Docs: Customizing IntelliSense](https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense)

It's possible but how come it only started happening a few weeks ago?

And also why does this only happen in `.astro` files not in `.svelte` or even `.jsx` files?

It could very well be something on my end... but I've been using Astro for a couple of years now and AFAIK the only thing that has changed is the Astro tools extension.

**Comment by PierBover** [comment]
@Princesseuh I'm not sure how I could send you a repro. The issue is not in the `.astro` files themselves.

I just crested a new empty Astro project with 4.5.5, VSCode 1.87.2, and v2.8.3 of the tools. I'm not seeing the issue on this project.

It must be something on that other project. If I ever figured it out I will reopen this issue.

**Comment by Princesseuh** [comment]
Okay, no worries! I'm sorry for the inconvenience, would've loved to investigate and fix this!

**Comment by PierBover** [comment]
I haven't figured out the origin of the issue yet but I'm still having problems even in new empty Astro projects.

For example if I have a word and write a period `.` right after it I get these file completions:

<img width="803" alt="image" src="https://github.com/withastro/language-tools/assets/226483/f882a528-6b7c-4641-8d61-26f4736793fd">

Which produces a JS import.

This would make sense inside a tag to import a component or maybe right after a `<` character. But this happens in regular HTML text.

I'm not reopening the issue yet because it's not clear what's causing this. It does seem like it's the Astro dev tools though.
