### ISSUE TITLE
🐛 BUG: autocomplete does not work with inline style when Japanese text is included in an element.

### ISSUE THREAD

**Issue by tsukashu** [withastro/language-tools#862]
### Describe the Bug

When Japanese text is included in an element, autocompletion with inline style attributes does not work **after** the location where the Japanese text appears.And, it may not work on any element after that.

### Steps to Reproduce

1. Install VSCode Version: 1.88.x (I use Portable version)
2. `npm create astro@latest "--" --template minimal -n`
3. Add Latest Astro VSCode Extension and install npm packages include the template.
4. Add some Japanese elements.
5. First Japanese elements, autocomplete with inline style works fine, but after all elements will not work.

https://github.com/withastro/language-tools/assets/80503344/45cef9a8-d79e-49b1-bf4d-acea20c1f2d1

thank you for your efforts.

**Comment by Princesseuh** [comment]
Might be related to https://github.com/withastro/language-tools/issues/660, thank you for reporting this issue, we'll take a look as soon as possible!
