### ISSUE TITLE
🐛 BUG: Installation of `@astrojs/react` leads to failure of `astro check`

### ISSUE THREAD

**Issue by metters** [withastro/language-tools#885]
### Describe the Bug

`astro check` worked before I installed @astrojs/react, but now it does not anymore.

The expected value of `satori` changes from `VNode` to `ReactNode` due to that installation:
<img width="500" alt="Screenshot 2024-06-25 at 21 41 41" src="https://github.com/withastro/language-tools/assets/9088722/b1ed3224-e2b6-4889-9f98-21586f27075e">

The [run of the GitHub Action](https://github.com/metters/astro-theme-cactus/actions/runs/9668291032) failed on the [updated branch](https://github.com/metters/astro-theme-cactus/pull/2).

Before that it still worked (see other runs before, there are only two previous runs, both without @astrojs/react).

Is this a satori bug or an astro bug? Sorry, if this is the wrong repository to open an issue!

Thank you very much in advance!

### Steps to Reproduce

* Clone https://github.com/chrismwilliams/astro-theme-cactus
* Manually or automatically install [@astrojs/react](https://docs.astro.build/en/guides/integrations-guide/react/)
* Execute `astro check`
* Error: The check fails because the expected type of a method changed. See screenshot above

**Comment by Princesseuh** [comment]
This is unrelated to `astro check`, it's a quirk of how Satori works. When installing the React integration, you also install the types for React, which Satori then automatically uses.
