### ISSUE TITLE
🐛 BUG:Error reported for attribute vscode

### ISSUE THREAD

**Issue by ajiho** [withastro/language-tools#886]
### Describe the Bug

![image](https://github.com/withastro/language-tools/assets/107699138/6bb46d0e-2244-4848-8b00-5008f37c5ff2)

```
不能将类型“{ children: any[]; lang: string; myattr: any; }”分配给类型“HtmlHTMLAttributes”。
  类型“HtmlHTMLAttributes”上不存在属性“myattr”。ts(2322)
```
Why? This syntax can be compiled in Astro, but vscode reports an error, which I think is very unreasonable

### Steps to Reproduce

无

**Comment by Princesseuh** [comment]
Because the html element doesn't take that attribute normally. The type checking checks for standard attributes.

You can extend the type definition by following the second part of this section: https://docs.astro.build/en/guides/typescript/#built-in-html-attributes
