### ISSUE TITLE
🐛 BUG: Rename symbol doesn't work inside `<script>` tags, 

### ISSUE THREAD

**Issue by alexrecuenco** [withastro/language-tools#889]
### Describe the Bug

Two different issues. 

First, if I try to do `rename symbol` inside a <Script> tag it doesn't work,  I get "Rename failed to apply edits" (Try to rename `other` in the minimal example provided below)

Second, if I rename `token` in the following example I get token renamed inside define:vars and `<href>`, but not as a direct reference

Example, renaming `token`

1. Before rename

```astro
---
const token = "!@#$1234";
---

<script define:vars={{ token }}>
  const other = 1234; // <-- can't rename this "Rename failed to apply edits"
  console.log(token, other);
</script>

<div class="form-content">
  {token}
  <a aria-label="#" href=`http://my.api/${token}` />
</div>
```

2. After rename

```astro
---
const token2 = "!@#$1234";
---

<script define:vars={{ token: token2 }}>
  const other = 1234;
  console.log(token, other);
</script>

<div class="form-content">
  {token}
  <a aria-label="#" href=`http://my.api/${token2}` />
</div>

```

### Version information

- Astro extension Astro v2.10.2

- Relevant package.json

    ```json
            "astro": "^4.11.3",
            "typescript": "^5.5.2"
    ```

- vscode 

```txt
    Date: 2024-06-11T21:44:54.914Z (3 wks ago)
    Electron: 29.4.0
    ElectronBuildId: 9593362
    Chromium: 122.0.6261.156
    Node.js: 20.9.0
    V8: 12.2.281.27-electron.0
    OS: Darwin arm64 23.5.0
```

- OS version

```txt
    MacOS M2 14.5 (23F79)
```

**Comment by alexrecuenco** [comment]
I don't think it is quite like #496 , but maybe we should re-open that one instead

**Comment by alexrecuenco** [comment]
It could be! Go to symbol also doesn't work on my environment, I was just trying to fix this one issue at a time.

Do we know if this ever worked? To try to change extension versions.

**Comment by Princesseuh** [comment]
I think it's a recent regression, I wouldn't suggest going back in version *that much* like the issue you linked suggested. I think both issues will be fixed once I merge in https://github.com/withastro/language-tools/pull/879, which I'll be doing once I get back from holidays next week
