### ISSUE TITLE
🐛 BUG: Syntax highlighting is broken

### ISSUE THREAD

**Issue by openscript** [withastro/language-tools#901]
### Describe the Bug

![image](https://github.com/user-attachments/assets/6e6160ad-c435-451b-9174-a1bc97f26d2a)

### Steps to Reproduce

1. Clone https://github.com/openscript/astro-i18n-demo/tree/repro/refactor-astro-config-file-name
2. Open VSCode with Astro Extension `2.11.0`
3. Open an Astro file.

```
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.9.9-arch1-1
```

**Comment by Princesseuh** [comment]
This is not syntax highlighting, but semantic highlighting. I'll take a look, thank you!

**Comment by Princesseuh** [comment]
It seems to work just fine for me: 
<img width="506" alt="image" src="https://github.com/user-attachments/assets/d6f7f172-9c54-40dc-98fb-e16a6550603f">

Do you have more precise reproduction steps?

**Comment by openscript** [comment]
Thank you for looking into it. Now suddenly the issue seems to be gone :(
