### ISSUE TITLE
🐛 BUG: Astro import duplication bug

### ISSUE THREAD

**Issue by Zyruks** [withastro/language-tools#928]
### Describe the Bug

When enabling `organizeImports` in VSCode settings, saving a file in an Astro project duplicates the import statements, especially when using import aliases defined in `tsconfig.json`. This issue occurs in Astro v2.13.1 and v2.13.0 but not in v2.12.8.

**Environment:**
- OS: Windows 11 using WSL 2 with Ubuntu
- Astro version: v2.13.1 and v2.13.0
- VSCode version: 1.92.0 (system setup)
- Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
- Date: 2024-07-31T23:26:45.634Z
- Electron: 30.1.2
- ElectronBuildId: 9870757
- Chromium: 124.0.6367.243
- Node.js: 20.14.0
- V8: 12.4.254.20-electron.0
- VSCode extensions: astro-build.astro-vscode

**Additional Context:**
Disabling `organizeImports` resolves the issue temporarily. Reverting to version 2.12.8 resolves the issue as well.

**.vscode/settings.json**
![image](https://github.com/user-attachments/assets/232f9825-25c2-4acf-afde-371ed282d3cd)

**Bug in Action:**

https://github.com/user-attachments/assets/a479bef8-2d09-4ed4-8b91-31cbede0bd22

If you need more information or further details, please let me know.

### Steps to Reproduce

1. Install Astro v2.13.1 or v2.13.0.
2. Enable `organizeImports` in the VSCode settings.
3. Define import aliases in `tsconfig.json` (e.g., `@components`, `@layouts`).
4. Create a file with multiple import statements using these aliases.
5. Save the file.
6. Observe the duplicated import statements.

**Expected Behavior**

The import statements should not be duplicated upon saving.

**Actual Behavior**

Import statements are duplicated upon saving the file, particularly when using import aliases from `tsconfig.json`.

### Link to Minimal Reproducible Example

https://github.com/Zyruks/astro-import-duplication-bug

**Comment by Princesseuh** [comment]
I cannot seem to be able to reproduce this, and I'm not sure why that version would introduce that issue, but I'll take a look!

**Comment by Zyruks** [comment]
I have disabled all extensions, but the problem persists. You can try to reproduce the issue using the repository I uploaded.

[Link to Repo](https://github.com/Zyruks/astro-import-duplication-bug)

https://github.com/user-attachments/assets/6096e6d8-3476-4577-a60e-2dc6bd539e23

**Comment by Princesseuh** [comment]
Even with your repo, I cannot reproduce the issue. There's probably something else at play here, maybe Windows etc.

**Comment by Zyruks** [comment]
Well, if I can help or try anything else, just let me know.

**Comment by MattheousDT** [comment]
Can confirm this is also happening to me on Windows on all Astro repositories when I have organizeImports turned on. Reverting back to 2.12.8 likewise fixed the issue

**Comment by Princesseuh** [comment]
So far I have absolutely no idea what could cause this, the only difference between those two versions is the SCSS and LESS support, which should be totally unrelated to the frontmater 🤔

**Comment by Princesseuh** [comment]
@Zyruks @MattheousDT Does this still happen to you after the update?

**Comment by Princesseuh** [comment]
Yep, just figured out what's the reason. Working on a fix now! It only affects CRLF files, so at least it's possible to use LF as a workaround until a fix is released. Apologies for the inconvenience.

**Comment by Princesseuh** [comment]
It should be fixed in the last version, apologies for the delay, issue ended up being a bit complicated.
