### ISSUE TITLE
🐛 BUG: All vue files report errors after enabling the astro extension.

### ISSUE THREAD

**Issue by ikxin** [withastro/language-tools#932]
### Describe the Bug

After enabling the astro extension, many errors were reported in each Vue file, but as long as the astro extension is disabled, the errors disappear. This issue appeared in all Vue and Nuxt projects.

![QQ_1723304515157](https://github.com/user-attachments/assets/f48db638-6729-46af-9b89-c9a68c4ac27a)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

### Link to Minimal Reproducible Example

https://github.com/withastro/language-tools

**Comment by Princesseuh** [comment]
Make sure you're using the latest version of the Vue extension, as there's recently been issues where people would get stuck on old versions of their extension.

**Comment by ikxin** [comment]
@Princesseuh That's true! The vue extension has been kept in version v2.0.10. It turned out to be a problem with the vue extension. I'm very sorry!

**Comment by Princesseuh** [comment]
No worries, it happens!
