### ISSUE TITLE
🐛 BUG: Extension is slow when using TypeScript 5.6

### ISSUE THREAD

**Issue by Princesseuh** [withastro/language-tools#970]
### Describe the Bug

TS 5.6 seems to have changed something, and now the extension is quite slow. Probably that https://github.com/volarjs/typescript-auto-import-cache requires an update for this. 

Keeping this issue around as a refuge for fellow developers affected by this.

### Steps to Reproduce

1. Open an Astro project with TS 5.6 installed
2. Make sure the extension is using the workspace's version, so that it uses 5.6 if your version of VS Code doesn't use 5.6 by default.
3. Observe slowness.

### Link to Minimal Reproducible Example

N/A. Any repo with the correct version is affected.

**Comment by alicercedigital** [comment]
Thank you very much for open this issue! We were having this issue in our project where every time we saved an .astro file, it took about 2 to 4 seconds to save. We were starting to think that Astro might struggle with larger or more "complex" projects, but after switching from TypeScript version 5.6.3 to 5.5.4, everything works fine now.

**Comment by DrJume** [comment]
We have the same problem with Vue language tools, autocomplete inside Vue SFC files takes forever in a big monorepo project :(

**Comment by crazed-developer** [comment]
I'm hit severely with these performance problems, I'm fairly sure the issue are with the Astro extension. As i'm kind of able to remedy the issue. But with a caveat. 

So in an astro file, i do a database search and intellisensing like this:
results[0].  <-- 12 seconds later i get intellisense on the object

If i then switch the language directly to Typescript from Astro, in the bottom right corner of the vscode window.

Then intellisense reacts so fast my finger on the . has not even left the key.

The caveat being that now the global Astro object are not recocnized with types.

I'm having this issue on my two Macbook Pros
 * 2024 M3 36 GB
 * 2018 i9 32 GB

I hope this observation can help diagnose the problem.

Kind regards
Steffen

**Comment by johnsoncodehk** [comment]
This issue should have been fixed by https://github.com/volarjs/typescript-auto-import-cache/pull/6 and will be resolved with the next Astro extension release.

**Comment by Princesseuh** [comment]
Unfortunately, it does not fix the issue. It makes it better, but there's still work to be done here. I suspect a fix is needed in Volar itself

**Comment by Princesseuh** [comment]
https://github.com/volarjs/volar.js/pull/242 seems to fix this, at least partially. It's massively faster (by 410ms on my computer), but further optimisations can most likely bring this lower.

**Comment by crazed-developer** [comment]
> [volarjs/volar.js#242](https://github.com/volarjs/volar.js/pull/242) seems to fix this, at least partially. It's massively faster (by 410ms on my computer), but further optimisations can most likely bring this lower.

I hope for a quick release, thanks for your help!

**Comment by alicercedigital** [comment]
This problem keeps happening. We need to use TypeScript version 5.5.4 to work on the project. If we use any version above that, IntelliSense becomes very slow, taking several seconds to respond, and saving files also takes longer. With version 5.5.4, everything works fine.  

We are currently using:  
- Astro version 5.0.9  
- Extension version v2.15.4
