### ISSUE TITLE
🐛 BUG: VSCode extension is not verified

### ISSUE THREAD

**Issue by rambleraptor** [withastro/language-tools#975]
### Describe the Bug

The VSCode extension creator (withastro.com) is not verified, so the blue checkmark does not appear on the Marketplace. This is a substantial way to avoid having the extension look malicious.

### Steps to Reproduce

Compare https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode with https://marketplace.visualstudio.com/items?itemName=ms-python.python.

### Link to Minimal Reproducible Example

https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode

**Comment by Princesseuh** [comment]
We've sent the request already, waiting for Microsoft to approve it. We were verified before but lost it for some reason.

**Comment by Princesseuh** [comment]
They accepted it, closing this issue! Thank you.
